---
title: "Repot Analyses"
author: "Gabe Runte"
date: "2024-01-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(janitor)
library(RColorBrewer)
library(tidyverse)

gg_soilcolor = scale_color_manual(name = "Soil condition", breaks = c("P", "Q", "C"), 
                                  labels = c("Bigcone", "Oak", "Control"),
                                  values = c("#2A0944", "#3FA796", "#FEC260"))

gg_soilfill = scale_fill_manual(name = "Soil condition", breaks = c("P", "Q", "C"), 
                                  labels = c("Bigcone", "Oak", "Control"),
                                  values = c("#2A0944", "#3FA796", "#FEC260"))


gg_droughtcolor = scale_color_manual(name = "Watering trt.", breaks = c("D", "C"), 
                                     labels = c("Droughted", "Watered"),
                                  values = c("#fc6603", "#1a8899"))
gg_droughtfill = scale_fill_manual(name = "Watering trt.", breaks = c("D", "C"), 
                                     labels = c("Droughted", "Watered"),
                                  values = c("#fc6603", "#1a8899"))
```


```{r, message = F}
measure = read_csv(here("data", "analysis/size_master.csv"))
harvest = read_csv(here("data", "analysis/harvest_metrics.csv")) 
health = read_csv(here("data", "analysis/ndvi_data.csv"))
harvest_tips = read_csv(here("data", "analysis/harvest_roottips - all.csv"))
harvest_mass = read_csv(here("data", "harvest", "harvest_biomass_wideclean.csv"))
image_data = read_csv(here("data", "wide_final_seedling_area.csv"))
neighb_pairs = read_csv(here("data", "design", "ghecto_neighbor_pairs.csv"))
trt = read_csv(here("data", "design", "seedling_treatments.csv"))
drought = read_csv(here("data", "design", "drought_assignments_bypot.csv")) %>% 
  select(1,3)
harvest_comm = read_csv( here("data", "harvest", "harvest_community_matrix_scaled.csv"))
#for relative growth
repot_scan = read_csv(here("data/repotting", "seedling_scan_data.csv")) %>% 
  select(-seedling_sp, -notes)
```

```{r}
colonization = harvest_tips %>% mutate(harvest_col = colonized/(colonized+uncolonized)) %>% 
              select(seedling_id, harvest_col) %>% 
              mutate(seedling_id = as.numeric(seedling_id))

drought_treat = health %>% 
  select(seedling_id, treatment) %>% distinct()

total_treat = measure %>% 
  select(seedling_id, seedling_sp, soil_type, neighbor, neighb_sp, neighb_st, pot) %>% distinct() %>% drop_na()

image_df = image_data %>% left_join(total_treat) %>% 
  mutate(total_foliar = foliar+predawn_foliar+midday_foliar) %>% 
  left_join(drought_treat)

sort_string_chars <- function(s) {
  paste(sort(unlist(strsplit(s, ""))), collapse = "")
}

pot_df = neighb_pairs %>% 
  rename(seedling_id = seedling_1) %>% 
  left_join(trt) %>% 
  rename(sp1 = seedling_sp, st1 = soil_type) %>% 
  select(!seedling_id) %>% 
  rename(seedling_id = seedling_2) %>% 
  left_join(trt)%>% 
  rename(sp2 = seedling_sp, st2 = soil_type) %>% 
  mutate(spp = paste0(sp1, sp2))%>% 
  mutate(stt = paste0(st1, st2)) %>% 
  select(pot, spp, stt) %>% 
  mutate(spp = map_chr(spp, sort_string_chars)) %>% #alphabetize the combo to minimize different uniques
  mutate(stt = map_chr(stt, sort_string_chars)) %>% 
  left_join(drought)
```

RS Ratio
```{r}
df1 = harvest_mass %>% 
  left_join(total_treat) %>% 
  mutate(rf_ratio = root/foliar)%>% 
  mutate(rs_ratio = root/(shoot+foliar)) %>% 
  filter(is.finite(rs_ratio))%>% 
  mutate(st_long = case_when(
    soil_type == "P" ~ "Bigcone soil",
    soil_type == "Q" ~ "Oak soil",
    soil_type == "C" ~ "Sterile soil"
  ))%>% 
  mutate(sp_long = case_when(
    seedling_sp == "P" ~ "Bigcone",
    seedling_sp == "Q" ~ "Oak"
  )) %>% 
  mutate(total = root+shoot+foliar) %>% 
  left_join(drought_treat) %>% 
  filter(is.finite(rf_ratio)) %>% 
  select(-treatment) %>% 
  left_join(drought_treat)%>% 
  mutate(nsp_same = seedling_sp == neighb_sp)

TukeyHSD(aov(lm(rs_ratio~soil_type*neighb_st, data = df1 %>% 
           filter(seedling_sp == "P"))))

TukeyHSD(aov(lm(rs_ratio~soil_type*neighb_st, data = df1 %>% 
           filter(seedling_sp == "Q"))))


ggplot(df1 %>%  filter(rs_ratio<20), aes(x = sp_long, y = rs_ratio, fill = soil_type, color = neighb_st))+
  geom_boxplot(alpha = 0.75)+gg_soilfill+theme_minimal()+ 
  labs(x = "Seedling Species", y = "Root:Shoot Ratio")

TukeyHSD(aov(lm(log(rf_ratio)~soil_type*neighb_st, data = df1 %>% 
           filter(seedling_sp == "P"))))

TukeyHSD(aov(lm(log(rf_ratio)~soil_type*neighb_st, data = df1 %>% 
           filter(seedling_sp == "Q"))))

ggplot(df1 %>%  filter(rs_ratio<20), aes(x = sp_long, y = log(rf_ratio), fill = soil_type, color = neighb_st))+
  geom_boxplot(alpha = 0.75)+gg_soilfill+theme_minimal()+ 
  labs(x = "Seedling Species", y = "log(Root:Foliar Ratio)")
```


```{r}
ggplot(df1 %>% 
         filter(seedling_sp == "P"), aes(x = soil_type, y = root, fill = treatment))+
  geom_boxplot()+gg_droughtfill
```

```{r}
dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "P") 

ggplot(dfrs, aes(x = treatment, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))



dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = treatment, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "C")

ggplot(dfrs, aes(x = treatment, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "P") 

ggplot(dfrs, aes(x = treatment, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = treatment, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "C") %>% 
  filter(neighb_sp=="Q")

ggplot(dfrs, aes(x = treatment, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))
```

```{r}
dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "P") 

ggplot(dfrs, aes(x = neighb_st, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = neighb_st, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "C")

ggplot(dfrs, aes(x = neighb_st, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "P") 

ggplot(dfrs, aes(x = neighb_st, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = neighb_st, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "C") %>% 
  filter(neighb_sp=="Q")

ggplot(dfrs, aes(x = neighb_st, y = rs_ratio, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


```


Total size
```{r}
ggplot(df1, aes(x = sp_long, y = total, fill = soil_type, color = treatment))+
  geom_boxplot(alpha = 0.75)+gg_soilfill+theme_minimal()+ gg_droughtcolor+
  labs(x = "Seedling Species", y = "Total biomass (g)")+
  facet_wrap(~sp_long, scales = "free")
```


```{r}
TukeyHSD(aov(lm((rs_ratio)~soil_type, data = df1 %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm((root)~soil_type, data = df1 %>% 
           filter(seedling_sp == "Q"))))

TukeyHSD(aov(lm((root)~soil_type*treatment, data = df1 %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm((root)~soil_type*treatment, data = df1 %>% 
           filter(seedling_sp == "Q"))))

TukeyHSD(aov(lm((root)~soil_type*neighb_sp, data = df1 %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm((total)~soil_type*neighb_sp, data = df1 %>% 
           filter(seedling_sp == "Q"))))

TukeyHSD(aov(lm((rs_ratio)~soil_type*neighb_st, data = df1 %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm((root)~soil_type*neighb_st, data = df1 %>% 
           filter(seedling_sp == "Q"))))

```

Above but relativized to change since repotting


```{r}
harvest_mass

repot_scan 

rel_df = harvest_mass %>% 
  mutate(h_above = shoot+foliar, h_below = root) %>% 
  select(seedling_id, h_above, h_below) %>% 
  left_join(repot_scan %>% 
              rename(r_above = above_area_cm2, r_below = underground_area_cm2) %>%  select(-height_cm)) %>% 
  left_join(total_treat) %>% 
  mutate(above = h_above/r_above, below = h_below/r_below, total = (h_above+h_below)/(r_above+r_below)) %>% 
  mutate(rs = (h_below/h_above)/(r_below/r_above)) %>% 
  left_join(drought_treat)
```

```{r}

TukeyHSD(aov(lm(rs~soil_type, data = rel_df %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm(below~soil_type, data = rel_df %>% 
           filter(seedling_sp == "Q"))))

TukeyHSD(aov(lm(below~soil_type*treatment, data = rel_df %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm(below~soil_type*treatment, data = rel_df %>% 
           filter(seedling_sp == "Q"))))

TukeyHSD(aov(lm(below~soil_type*neighb_sp, data = rel_df %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm(below~soil_type*neighb_sp, data = rel_df %>% 
           filter(seedling_sp == "Q"))))

TukeyHSD(aov(lm(below~soil_type*neighb_st, data = rel_df %>% 
           filter(seedling_sp == "P"))))
TukeyHSD(aov(lm(below~soil_type*neighb_st, data = rel_df %>% 
           filter(seedling_sp == "Q"))))
```



```{r}
dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "P")

ggplot(dfrs, aes(x = treatment, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = treatment, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "C")

ggplot(dfrs, aes(x = treatment, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "P")

ggplot(dfrs, aes(x = treatment, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = treatment, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "C")%>% 
  filter(neighb_sp == "Q")

ggplot(dfrs, aes(x = treatment, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(neighb_st), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))
```

```{r}
dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "P") 

ggplot(dfrs, aes(x = neighb_st, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = neighb_st, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "C")

ggplot(dfrs, aes(x = neighb_st, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "P") 

ggplot(dfrs, aes(x = neighb_st, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "Q")

ggplot(dfrs, aes(x = neighb_st, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))

dfrs = df1 %>% 
  filter(seedling_sp == "Q") %>% 
  filter(soil_type == "C") %>% 
  filter(neighb_sp=="Q")

ggplot(dfrs, aes(x = neighb_st, y = total, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(cols = vars(treatment), rows = vars(neighb_sp))+
  gg_droughtcolor+gg_soilfill+theme_minimal()+lims(y = c(0,5))


```


##### Relative dataset

```{r}

```

