---
title: "Untitled"
author: "Gabe Runte"
date: "2024-01-30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(janitor)
library(RColorBrewer)
library(tidyverse)

gg_soilcolor = scale_color_manual(name = "Soil condition", breaks = c("P", "Q", "C"), labels = c("Bigcone", "Oak", "Control"),
                                  values = c("#2A0944", "#3FA796", "#FEC260"))
```


I begin by reading in the relevant data.
```{r, message = F}
measure = read_csv(here("data", "analysis/size_master.csv"))
harvest = read_csv(here("data", "analysis/harvest_metrics.csv")) 
health = read_csv(here("data", "analysis/ndvi_data.csv"))
harvest_tips = read_csv(here("data", "analysis/harvest_roottips - all.csv"))
harvest_mass = read_csv(here("data", "harvest", "harvest_biomass_wideclean.csv"))
repot_tips = read_csv(here("data", "repotting/ghecto_repotting_root_pulling_data.csv"))
image_data = read_csv(here("data", "wide_final_seedling_area.csv"))
neighb_pairs = read_csv(here("data", "design", "ghecto_neighbor_pairs.csv"))
trt = read_csv(here("data", "design", "seedling_treatments.csv"))
drought = read_csv(here("data", "design", "drought_assignments_bypot.csv")) %>% 
  select(1,3)

repot_comm = read_csv(here("data", "repotting", "repot_community_matrix_scaled.csv")) 
harvest_comm = read_csv( here("data", "harvest", "harvest_community_matrix_scaled.csv"))

repot_scan = read_csv(here("data/repotting", "seedling_scan_data.csv")) %>% 
  select(-seedling_sp, -notes)
```

```{r}
colonization = repot_tips %>% 
  mutate(repot_col = colonization_numerator/colonization_denominator) %>% 
  select(seedling_id, repot_col) %>% 
  left_join(harvest_tips %>% mutate(harvest_col = colonized/(colonized+uncolonized)) %>% 
              select(seedling_id, harvest_col) %>% 
              mutate(seedling_id = as.numeric(seedling_id)))

drought_treat = health %>% 
  select(seedling_id, treatment) %>% distinct()

total_treat = measure %>% 
  select(seedling_id, seedling_sp, soil_type, neighbor, neighb_sp, neighb_st, pot) %>% distinct() %>% drop_na()

image_df = image_data %>% left_join(total_treat) %>% 
  mutate(total_foliar = foliar+predawn_foliar+midday_foliar) %>% 
  left_join(drought_treat)

sort_string_chars <- function(s) {
  paste(sort(unlist(strsplit(s, ""))), collapse = "")
}

pot_df = neighb_pairs %>% 
  rename(seedling_id = seedling_1) %>% 
  left_join(trt) %>% 
  rename(sp1 = seedling_sp, st1 = soil_type) %>% 
  select(!seedling_id) %>% 
  rename(seedling_id = seedling_2) %>% 
  left_join(trt)%>% 
  rename(sp2 = seedling_sp, st2 = soil_type) %>% 
  mutate(spp = paste0(sp1, sp2))%>% 
  mutate(stt = paste0(st1, st2)) %>% 
  select(pot, spp, stt) %>% 
  mutate(spp = map_chr(spp, sort_string_chars)) %>% #alphabetize the combo to minimize different uniques
  mutate(stt = map_chr(stt, sort_string_chars)) %>% 
  left_join(drought)
```


### RELATIVIZED GROWTH

```{r}
repot_rel = repot_scan %>% 
  left_join(trt) %>% 
  mutate(total = above_area_cm2+underground_area_cm2) %>% 
  group_by(seedling_sp) %>% 
  mutate(repot_above = (above_area_cm2-mean(above_area_cm2))/sd(above_area_cm2))%>% 
  mutate(repot_below = (underground_area_cm2-mean(underground_area_cm2))/sd(underground_area_cm2)) %>% 
  mutate(rs_ratio = underground_area_cm2/above_area_cm2) %>% 
  mutate(repot_total = (total-mean(total))/sd(total)) %>% 
  mutate(repot_rs_ratio = (rs_ratio-mean(rs_ratio))/sd(rs_ratio)) %>% 
  ungroup() %>% 
  select(seedling_id, repot_above, repot_below, repot_rs_ratio, repot_total)

harvest_rel = harvest_mass %>% 
  left_join(trt) %>% 
  mutate(total = root+shoot+foliar) %>% 
  group_by(seedling_sp) %>% 
  drop_na() %>% 
  filter(shoot>0) %>% 
  mutate(harvest_above = (shoot -mean(shoot))/sd(shoot))%>% 
  mutate(harvest_below = (root -mean(root))/sd(root)) %>% 
  mutate(harvest_foliar = (foliar -mean(foliar))/sd(foliar))%>% 
  mutate(harvest_total = (total -mean(total))/sd(total))%>% 
  mutate(rs_ratio = (root+foliar)/shoot) %>% 
  mutate(harvest_rs_ratio = (rs_ratio -mean(rs_ratio))/sd(rs_ratio)) %>% 
  ungroup()%>% 
  select(seedling_id, harvest_above, harvest_below, harvest_rs_ratio, harvest_total)


rel_growth = repot_rel %>% 
  left_join(harvest_rel) %>% 
  left_join(total_treat) %>% 
  drop_na() %>% 
  left_join(drought_treat) %>% 
  mutate(rs_grow = harvest_rs_ratio - repot_rs_ratio) %>% 
  mutate(above_grow = harvest_above-repot_above)%>% 
  mutate(below_grow = harvest_below-repot_below)%>% 
  mutate(total_grow = harvest_total-repot_total)%>% 
  mutate(st_long = case_when(
    soil_type == "P" ~ "Bigcone soil",
    soil_type == "Q" ~ "Oak soil",
    soil_type == "C" ~ "Sterile soil"
  ))%>% 
  mutate(sp_long = case_when(
    seedling_sp == "P" ~ "Bigcone",
    seedling_sp == "Q" ~ "Oak"
  ))
```
relative rs
```{r}
ggplot(rel_growth, aes(x = treatment, y = rs_grow, fill = soil_type, color = treatment))+
  geom_boxplot()+facet_grid(rows = vars(sp_long), cols = vars(st_long), scales = "free")+
  gg_soilfill+gg_droughtcolor+theme_minimal()+lims(y = c(-4,4))


df1 = rel_growth %>% 
  filter(seedling_sp == "P") %>% 
  filter(soil_type == "P")

ggplot(df1, aes(x = treatment, y = total_grow, fill = neighb_st, color = treatment))+
  geom_boxplot()+facet_grid(rows = vars(neighb_sp), cols = vars(neighb_st), scales = "free")+
  gg_soilfill+gg_droughtcolor+theme_minimal()+lims(y = c(-4,4))

# t.test(above_grow ~ treatment, data = df1 %>%
#          filter(neighb_sp == "Q")%>%
#          filter(neighb_st == "P"))
```

Something about competitive ability and the outcome through drought? 






