---
title: "results"
author: "Gabe Runte"
date: "2024-07-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(janitor)
library(RColorBrewer)
# library(ISLR)
library(rpart)
library(rpart.plot)
# library(vip)
library(rattle)
library(dismo)
library(patchwork)
library(tidyverse)

source(here("src", "colors.R"))
```

## Read in files
```{r, message = F}
measure = read_csv(here("data", "analysis/size_master.csv"))
harvest = read_csv(here("data", "analysis/harvest_metrics.csv")) 
health = read_csv(here("data", "analysis/ndvi_data.csv"))
harvest_tips = read_csv(here("data", "analysis/harvest_roottips - all.csv")) %>% 
  filter(!is.na(seedling_id))
repot_tips = read_csv(here("data", "repotting/ghecto_repotting_root_pulling_data.csv"))
harvest_mass = read_csv(here("data", "harvest", "harvest_biomass_wideclean.csv"))
image_data = read_csv(here("data", "wide_final_seedling_area.csv"))
repot_mass = read_csv(here("data", "repotting", "repotting_drymass_fitted.csv"))
neighb_pairs = read_csv(here("data", "design", "ghecto_neighbor_pairs.csv"))
trt = read_csv(here("data", "design", "seedling_treatments.csv"))
drought = read_csv(here("data", "design", "drought_assignments_bypot.csv")) %>% select(1,3)
harvest_comm = read_csv( here("data", "harvest", "harvest_community_matrix_scaled.csv"))

pressure = read_csv(here("data/harvest", "pressure_bomb - Sheet1.csv")) %>% select(1:4) %>%  mutate(time = tolower(time))
sapwood = read_csv(here("data/harvest", "harvest_sapwood.csv"))
```

### Edit/compile some files
```{r, warning = F, message=F}
colonization = repot_tips %>% 
  mutate(repot_col = case_when(
    colonization_numerator == 0 ~ 0,
    .default = colonization_numerator/colonization_denominator)) %>% 
  select(seedling_id, repot_col) %>% 
  left_join(harvest_tips %>% 
              mutate(harvest_col = case_when(
                    colonized == 0 ~ 0,
                    .default =colonized/(colonized+uncolonized))) %>% 
              select(seedling_id, harvest_col) %>% 
              mutate(seedling_id = as.numeric(seedling_id)))

drought_treat = health %>% 
  select(seedling_id, treatment) %>% distinct()

total_treat = measure %>% 
  select(seedling_id, seedling_sp, soil_type, neighbor, neighb_sp, neighb_st, pot) %>% distinct() %>% drop_na() %>% left_join(drought_treat)

sort_string_chars <- function(s) {
  paste(sort(unlist(strsplit(s, ""))), collapse = "")}

pot_df = neighb_pairs %>% 
  rename(seedling_id = seedling_1) %>% 
  left_join(trt) %>% 
  rename(sp1 = seedling_sp, st1 = soil_type) %>% 
  select(!seedling_id) %>% 
  rename(seedling_id = seedling_2) %>% 
  left_join(trt)%>% 
  rename(sp2 = seedling_sp, st2 = soil_type) %>% 
  mutate(spp = paste0(sp1, sp2))%>% 
  mutate(stt = paste0(st1, st2)) %>% 
  select(pot, spp, stt) %>% 
  mutate(spp = map_chr(spp, sort_string_chars)) %>% #alphabetize the combo to minimize different uniques
  mutate(stt = map_chr(stt, sort_string_chars)) %>% 
  left_join(drought)

living = measure %>% 
  filter(date == "2022-04-01") %>% 
  filter(alive ==1)  %>% 
  select(seedling_id)
```


## Mass and relative growth
```{r}
grow_mass = repot_mass %>% 
  rename(r_shoot = above_dry, r_root = below_dry) %>% 
  mutate(r_rs = r_root/r_shoot) %>%
  mutate(r_total = r_root+r_shoot) %>%
  left_join(harvest_mass %>% 
              mutate(shoot = shoot +foliar) %>%  select(-foliar) %>% 
              rename(h_shoot = shoot, h_root = root) %>% 
              mutate(h_rs = h_root/h_shoot)) %>%
              mutate(h_total = h_root+h_shoot)%>% 
  mutate(grow_root = (h_root-r_root)/r_root)%>% 
  mutate(grow_shoot = (h_shoot-r_shoot)/r_shoot) %>% 
  mutate(grow_rs = log(h_rs/r_rs)) %>% 
  mutate(grow_total = ((h_total-r_total)/r_total)) %>%
  mutate(soil_type = fct_relevel(soil_type, c("P", "Q", "C"))) %>% 
  left_join(drought_treat) %>% 
  left_join(total_treat) %>% 
  left_join(repot_mass %>% 
              mutate(n_total = above_dry+below_dry) %>% 
              select(seedling_id, n_total) %>%  rename(neighbor = seedling_id)) %>% 
  mutate(n_rel = r_total/n_total) %>% 
  filter(seedling_id %in% living$seedling_id)

grow_mass_all = repot_mass %>% 
  rename(r_shoot = above_dry, r_root = below_dry) %>% 
  mutate(r_rs = r_root/r_shoot) %>%
  mutate(r_total = r_root+r_shoot) %>%
  left_join(harvest_mass %>% 
              mutate(shoot = shoot +foliar) %>%  select(-foliar) %>% 
              rename(h_shoot = shoot, h_root = root) %>% 
              mutate(h_rs = h_root/h_shoot)) %>%
              mutate(h_total = h_root+h_shoot)%>% 
  mutate(grow_root = (h_root-r_root)/r_root)%>% 
  mutate(grow_shoot = (h_shoot-r_shoot)/r_shoot) %>% 
  mutate(grow_rs = log(h_rs/r_rs)) %>% 
  mutate(grow_total = ((h_total-r_total)/r_total)) %>%
  mutate(soil_type = fct_relevel(soil_type, c("P", "Q", "C"))) %>% 
  left_join(drought_treat) %>% 
  left_join(total_treat) %>% 
  left_join(repot_mass %>% 
              mutate(n_total = above_dry+below_dry) %>% mutate(nroot = below_dry) %>% 
              select(seedling_id, n_total, nroot) %>%  rename(neighbor = seedling_id)) %>% 
  mutate(n_rel = r_total/n_total)%>% 
  mutate(n_relroot = r_root/nroot)

rel_size = grow_mass %>% 
  select(seedling_id, r_total, r_root) %>% 
  left_join(total_treat) %>% 
  group_by(seedling_sp) %>% ##changing this as of 09/04/2024
  mutate(avg_mass = (r_total-mean(r_total, na.rm = T))/sd(r_total, na.rm = T)) %>% 
  mutate(avg_rootmass = (r_root-mean(r_root, na.rm = T))/sd(r_root, na.rm = T)) %>% 
  ungroup() %>% 
  select(seedling_id, avg_mass, avg_rootmass) %>% 
  rename(rel_mass = avg_mass)%>% 
  rename(rel_rootmass = avg_rootmass)

rel_final = grow_mass %>% 
  select(seedling_id, h_total, h_root) %>% 
  left_join(total_treat) %>% 
  group_by(seedling_sp, soil_type, neighb_sp, neighb_st) %>% 
  mutate(avg_mass = (h_total-mean(h_total, na.rm = T))/sd(h_total, na.rm = T))%>% 
  mutate(avg_rootmass = (h_root-mean(h_root, na.rm = T))/sd(h_root, na.rm = T)) %>% 
  ungroup() %>% 
  select(seedling_id, avg_mass, avg_rootmass) %>% 
  rename(rel_hmass = avg_mass)%>% 
  rename(rel_hrootmass = avg_rootmass)

n_relsize = rel_size %>% 
  rename(neighbor = seedling_id, n_relmass = rel_mass, n_rel_rootmass = rel_rootmass)


rel_set = rel_size %>% 
  left_join(rel_final) %>% 
  left_join(total_treat) %>% 
  left_join(n_relsize) %>% 
  left_join(drought_treat) %>% 
  left_join(grow_mass) %>% 
  mutate(rel = rel_mass-n_relmass) %>% 
  mutate(rel = rel_mass-n_relmass) %>% 
  mutate(relroot = rel_rootmass-n_rel_rootmass) 

ndvi = health %>% 
  group_by(seedling_id) %>% 
  summarize(ndvi_change = max(mean_ndvi)-min(mean_ndvi),
            ndvi = mean(mean_ndvi), 
            min_ndvi = min(mean_ndvi)) %>% 
  left_join(total_treat)%>% 
  mutate(home_rank = case_when(
    soil_type == seedling_sp & neighb_sp == soil_type & soil_type==neighb_st ~ "Both",
    soil_type == seedling_sp ~ "Self",
    seedling_sp == neighb_st ~ "Neighbor",
    .default = "None"
  )) %>% 
  mutate(home_rank = factor(home_rank, levels = c("None", "Neighbor", "Self", "Both"))) %>% 
  filter(!is.na(seedling_sp)) %>% 
  filter(seedling_id %in% living$seedling_id)
```


```{r}
gbm_data_ptot = grow_mass %>%filter(seedling_sp == "P") %>% 
  left_join(colonization %>% select(1:2))%>% 
  dplyr::select(h_total, soil_type, neighb_sp, neighb_st, treatment, repot_col)  %>% 
  drop_na() %>% 
  mutate(h_total = as.numeric(h_total)) %>% 
  mutate(soil_type = as.factor(soil_type))%>% 
  mutate(neighb_sp = as.factor(neighb_sp))%>% 
  mutate(neighb_st = as.factor(neighb_st))%>% 
  mutate(treatment = as.factor(treatment))%>% 
  mutate(repot_col = as.numeric(repot_col))

best_p_total =  gbm.step(data = data.frame(gbm_data_ptot), gbm.x = 2:6, gbm.y = 1, family = "gaussian", step.size = 25,
                               learning.rate = 0.0005, bag.fraction = 0.6, tree.complexity = 2)

gbm.plot(best_p_total)
interactions = gbm.interactions(best_p_total)

best_inf = tibble(best_p_total$contributions) %>% 
  mutate(var = fct_reorder(var, rel.inf))

ggplot(best_inf, aes(x = var, y = rel.inf, fill = rel.inf))+
  geom_bar(stat= "identity")+labs(x = "Predictor", y="Relative Influence")+
  scale_fill_continuous(name = "Relative \nInfluence")+theme_minimal()

pbest_plot = best_inf %>% 
  mutate(var = case_when(
    var== "soil_type" ~ "Soil type",
    var== "neighb_st" ~ "Neighbor soil",
    var== "treatment" ~ "Drought",
    var== "neighb_sp" ~ "Neighbor species",
    var== "repot_col" ~ "Fungal colonization"
  )) %>% 
  mutate(var = fct_reorder(var, rel.inf))

ggplot(pbest_plot, aes(x = var, y = rel.inf, fill = rel.inf))+
  geom_bar(stat= "identity")+labs(x = "Predictor", y="Relative Influence")+ 
  scale_fill_viridis_c(name = "Relative \nInfluence",direction = -1, option = "turbo")+theme_minimal()

ggplot(pbest_plot, aes(x = var, y = rel.inf))+
  geom_bar(stat= "identity", fill = "#5A745B", alpha = 0.75)+labs(x = "Predictor", y="Relative Influence")+theme_minimal()

```


```{r}
gbm_data_pndvi = grow_mass %>%filter(seedling_sp == "P") %>% 
  left_join(ndvi %>% select(1,3)) %>% 
  left_join(colonization %>% select(1:2)) %>% 
  dplyr::select(ndvi, soil_type, neighb_sp, neighb_st, treatment, repot_col) %>% 
  drop_na() %>% 
  mutate(ndvi = as.numeric(ndvi)) %>% 
  mutate(soil_type = as.factor(soil_type))%>% 
  mutate(neighb_sp = as.factor(neighb_sp))%>% 
  mutate(neighb_st = as.factor(neighb_st))%>% 
  mutate(treatment = as.factor(treatment))%>% 
  mutate(repot_col = as.numeric(repot_col))


best_p_ndvi =  gbm.step(data = data.frame(gbm_data_pndvi), gbm.x = 2:6, gbm.y = 1, family = "gaussian", step.size = 25,
                               learning.rate = 0.0005, bag.fraction = 0.6, tree.complexity = 2)

interactions = gbm.interactions(best_p_ndvi)

best_inf_pndvi = tibble(best_p_ndvi$contributions) %>% 
  mutate(var = fct_reorder(var, rel.inf))

ggplot(best_inf_pndvi, aes(x = var, y = rel.inf, fill = rel.inf))+
  geom_bar(stat= "identity")+labs(x = "Predictor", y="Relative Influence")+
  scale_fill_continuous(name = "Relative \nInfluence")+theme_minimal()
```


```{r}
pinf_plotset = pbest_plot %>% 
  mutate(Outcome = "Biomass") %>% 
  bind_rows(best_inf_pndvi %>% mutate(Outcome = "NDVI"))%>% 
  mutate(var = case_when(
    var== "soil_type" ~ "Soil type",
    var== "neighb_st" ~ "Neighbor soil",
    var== "treatment" ~ "Drought",
    var== "neighb_sp" ~ "Neighbor species",
    var== "repot_col" ~ "Fungal colonization",
    .default = var
  )) %>% 
  arrange(rel.inf)

p_combineplot = ggplot(pinf_plotset, aes(x = reorder(var, rel.inf), y = rel.inf, fill = Outcome))+
  geom_bar(stat= "identity",  alpha = 0.75, position= "dodge")+
  labs(x = "Predictor", y="Relative Influence")+theme_minimal()+
  scale_fill_manual(values = c("#5A745B", "darkgray"))

p_combineplot
p_combineplot+white_theme
```


```{r}
gbm_data_qtot = grow_mass %>%filter(seedling_sp == "Q") %>% 
  left_join(colonization %>% select(1:2))%>% 
  dplyr::select(h_total, soil_type, neighb_sp, neighb_st, treatment)  %>% 
  drop_na() %>% 
  mutate(h_total = as.numeric(h_total)) %>% 
  mutate(soil_type = as.factor(soil_type))%>% 
  mutate(neighb_sp = as.factor(neighb_sp))%>% 
  mutate(neighb_st = as.factor(neighb_st))%>% 
  mutate(treatment = as.factor(treatment)) 

best_q_total =  gbm.step(data = data.frame(gbm_data_qtot), gbm.x = 2:5, gbm.y = 1, family = "gaussian", step.size = .1,
                               learning.rate = 0.0000001, bag.fraction = 0.6, tree.complexity = 2)


best_inf_q = tibble(best_q_total$contributions) %>% 
  mutate(var = fct_reorder(var, rel.inf))

ggplot(best_inf_q, aes(x = var, y = rel.inf, fill = rel.inf))+
  geom_bar(stat= "identity")+labs(x = "Predictor", y="Relative Influence")+
  scale_fill_continuous(name = "Relative \nInfluence")+theme_minimal()
```


```{r}

gbm_data_qndvi = grow_mass %>%filter(seedling_sp == "Q") %>% 
  left_join(ndvi %>% select(1,3)) %>% 
  left_join(colonization %>% select(1:2)) %>% 
  dplyr::select(ndvi, soil_type, neighb_sp, neighb_st, treatment) %>% 
  drop_na() %>% 
  mutate(ndvi = as.numeric(ndvi)) %>% 
  mutate(soil_type = as.factor(soil_type))%>% 
  mutate(neighb_sp = as.factor(neighb_sp))%>% 
  mutate(neighb_st = as.factor(neighb_st))%>% 
  mutate(treatment = as.factor(treatment))



best_q_ndvi =  gbm.step(data = data.frame(gbm_data_qndvi), gbm.x = 2:5, gbm.y = 1, family = "gaussian", step.size = 1,
                               learning.rate = 0.00001, bag.fraction = 0.6, tree.complexity = 2)

interactions = gbm.interactions(best_q_ndvi)

best_inf_qndvi = tibble(best_q_ndvi$contributions) %>% 
  mutate(var = fct_reorder(var, rel.inf))

ggplot(best_inf_qndvi, aes(x = var, y = rel.inf, fill = rel.inf))+
  geom_bar(stat= "identity")+labs(x = "Predictor", y="Relative Influence")+
  scale_fill_continuous(name = "Relative \nInfluence")+theme_minimal()


```


```{r}
qinf_plotset = best_inf_q %>% 
  mutate(Outcome = "Biomass") %>% 
  bind_rows(best_inf_qndvi %>% mutate(Outcome = "NDVI"))%>% 
  mutate(var = case_when(
    var== "soil_type" ~ "Soil type",
    var== "neighb_st" ~ "Neighbor soil",
    var== "treatment" ~ "Drought",
    var== "neighb_sp" ~ "Neighbor species",
    .default = var
  )) %>% 
  group_by(Outcome) %>% 
  mutate(orderer = case_when(var=="Drought"~4, var=="Soil type"~3, var=="Neighbor soil"~2, var=="Neighbor species"~1)) %>% 
  mutate(Outcome = fct_reorder(Outcome, orderer))%>% 
  arrange(rel.inf)

q_col = tibble(var = rep("Fungal colonization", 2), rel.inf = rep(NA, 2), Outcome = c("NDVI", "Biomass"), orderer = rep(5, 2))

q_tot = bind_rows(qinf_plotset, q_col)

q_combineplot = ggplot(qinf_plotset, aes(x = reorder(var, orderer), y = rel.inf, fill = Outcome))+
  geom_bar(stat= "identity",  alpha = 0.75, position= "dodge")+
  labs(x = "Predictor", y="Relative Influence")+theme_minimal()+
  scale_fill_manual(values = c("#A46F00", "darkgray"))

q_combineplot
```



```{r}
both_inf_plot = p_combineplot/q_combineplot

cowplot::save_plot(plot = q_combineplot,
  base_height = 4,
  base_asp = 2,filename =  here("figures", "oak_combined_inf.jpg"))

cowplot::save_plot(plot = p_combineplot,
  base_height = 4,
  base_asp = 2,filename =  here("figures", "bigcone_combined_inf.jpg"))
```

```{r}
qinf_plotnew = best_inf_q %>% 
  mutate(Outcome = "Biomass") %>% 
  bind_rows(best_inf_qndvi %>% mutate(Outcome = "NDVI"))%>% 
  mutate(var = case_when(
    var== "soil_type" ~ "Soil type",
    var== "neighb_st" ~ "Neighbor soil",
    var== "treatment" ~ "Drought",
    var== "neighb_sp" ~ "Neighbor species",
    .default = var
  )) %>% 
  group_by(Outcome) %>% 
  mutate(orderer = case_when(var=="Drought"~5, var=="Soil type"~4, var=="Neighbor soil"~2, var=="Neighbor species"~1)) %>% 
  mutate(Outcome = fct_reorder(Outcome, orderer))%>% 
  arrange(rel.inf)

q_col = tibble(var = rep("Fungal colonization", 2), rel.inf = rep(NA, 2), Outcome = c("NDVI", "Biomass"), orderer = rep(3, 2))

q_tot = bind_rows(qinf_plotnew, q_col)

q_combinenew = ggplot(q_tot, aes(x = reorder(var, orderer), y = rel.inf, fill = Outcome))+
  geom_bar(stat= "identity",  alpha = 0.75, position= "dodge")+
  labs(x = "Predictor", y="Relative Influence")+theme_minimal()+
  scale_fill_manual(values = c("#A46F00", "darkgray"))+lims(y = c(0, 62))

q_combinenew


pinf_plotnew = pbest_plot %>% 
  mutate(Outcome = "Biomass") %>% 
  bind_rows(best_inf_pndvi %>% mutate(Outcome = "NDVI"))%>% 
  mutate(var = case_when(
    var== "soil_type" ~ "Soil type",
    var== "neighb_st" ~ "Neighbor soil",
    var== "treatment" ~ "Drought",
    var== "neighb_sp" ~ "Neighbor species",
    var== "repot_col" ~ "Fungal colonization",
    .default = var
  )) %>% 
  mutate(orderer = case_when(var=="Drought"~5, var=="Soil type"~4, var == "Fungal colonization"~3, var=="Neighbor soil"~2, var=="Neighbor species"~1)) %>% 
  mutate(Outcome = fct_reorder(Outcome, orderer))%>% 
  arrange(rel.inf)

p_combinenew = ggplot(pinf_plotnew, aes(x = reorder(var, orderer), y = rel.inf, fill = Outcome))+
  geom_bar(stat= "identity",  alpha = 0.75, position= "dodge")+
  labs(x = "Predictor", y="Relative Influence")+theme_minimal()+
  scale_fill_manual(values = c("#5A745B", "darkgray"))+lims(y = c(0, 60))

p_combinenew
```

```{r}
cowplot::save_plot(plot = q_combinenew,
  base_height = 4,
  base_asp = 2,filename =  here("figures", "oak_combined_new.jpg"))

cowplot::save_plot(plot = p_combinenew,
  base_height = 4,
  base_asp = 2,filename =  here("figures", "bigcone_combined_new.jpg"))
```
```{r}

p_combinenew_white = ggplot(pinf_plotnew, aes(x = reorder(var, orderer), y = rel.inf, fill = Outcome))+
  geom_bar(stat= "identity",  alpha = 0.95, position= "dodge")+
  labs(x = "Predictor", y="Relative Influence")+theme_minimal()+
  scale_fill_manual(values = c("#5A745B", "darkgray"))+lims(y = c(0, 62))+white_theme

q_combinenew_white = ggplot(q_tot, aes(x = reorder(var, orderer), y = rel.inf, fill = Outcome))+
  geom_bar(stat= "identity",  alpha = 0.95, position= "dodge")+
  labs(x = "Predictor", y="Relative Influence")+theme_minimal()+
  scale_fill_manual(values = c("#A46F00", "darkgray"))+lims(y = c(0, 62))+white_theme


# cowplot::save_plot(plot = q_combinenew_white,
#   base_height = 4,
#   base_asp = 3,filename =  here("figures", "oak_combined_new_white.png"))
# 
# cowplot::save_plot(plot = p_combinenew_white,
#   base_height = 4,
#   base_asp = 3,filename =  here("figures", "bigcone_combined_new_white.png"))


relative_bigcone = ggplot(pinf_plotnew, aes(x =rel.inf , y = Outcome, fill = reorder(var, orderer)))+
  geom_bar(stat= "identity",  alpha = 0.95, position= "stack")+
  labs(x = "Relative influence", y="")+theme_minimal()+no_grids+
  scale_fill_viridis_d(name = "Predictor", option = "D")

cowplot::save_plot(plot = relative_bigcone,
  base_height = 3,
  base_asp = 3,filename =  here("figures", "bigcone_relinf_white.png"))


relative_oak = ggplot(qinf_plotnew, aes(x =rel.inf , y = Outcome, fill = reorder(var, orderer)))+
  geom_bar(stat= "identity",  alpha = 0.95, position= "stack")+
  labs(x = "Relative influence", y="")+theme_minimal()+no_grids+
  scale_fill_viridis_d(name = "Predictor", option = "D")

cowplot::save_plot(plot = relative_oak,
  base_height = 3,
  base_asp = 3,filename =  here("figures", "oak_relinf_white.png"))


##########
relative_bigcone_bw = ggplot(pinf_plotnew, aes(x =rel.inf , y = Outcome, fill = reorder(var, orderer)))+
  geom_bar(stat= "identity",  alpha = 0.95, position= "stack")+
  labs(x = "Relative influence", y="")+theme_minimal()+no_grids+ 
  scale_fill_grey(name = "Predictor")


relative_bigcone_bw = ggplot(pinf_plotnew, aes(x = rel.inf, y = Outcome, fill = reorder(var, orderer))) +
  geom_bar(
    stat = "identity", 
    alpha = 0.95, 
    position = "stack", 
    color = "black",       # black outline on bars
    linewidth = 0.3
  ) +
  labs(x = "Relative influence", y = "") +
  scale_fill_manual(
    values = gray.colors(5, start = 0, end = 1),
    name = "Predictor",
    guide = guide_legend(override.aes = list(color = "black", size = 0.5))
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    panel.border = element_blank(),
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    plot.margin = margin(0, 0, 0, 0),
    legend.key = element_rect(color = "black", size = 0.5)
  )
relative_bigcone_bw
cowplot::save_plot(plot = relative_bigcone_bw,
  base_height = 2.5,
  base_asp = 3,filename =  here("figures", "bigcone_relinf_white_bw.png"))


relative_oak_bw = ggplot(qinf_plotnew, aes(x =rel.inf , y = Outcome, fill = reorder(var, orderer)))+
  geom_bar(stat= "identity",  alpha = 0.95, position= "stack")+
  labs(x = "Relative influence", y="")+theme_minimal()+no_grids+ 
  scale_fill_grey(name = "Predictor")

relative_oak_bw = ggplot(qinf_plotnew, aes(x = rel.inf, y = Outcome, fill = reorder(var, orderer))) +
  geom_bar(
    stat = "identity", 
    alpha = 0.95, 
    position = "stack", 
    color = "black",       # black outline on bars
    linewidth = 0.3
  ) +
  labs(x = "Relative influence", y = "") +
  scale_fill_manual(
    values = gray.colors(5, start = 0, end = 1),
    name = "Predictor",
    guide = guide_legend(override.aes = list(color = "black", size = 0.5))
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    panel.border = element_blank(),
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    plot.margin = margin(0, 0, 0, 0),
    legend.key = element_rect(color = "black", size = 0.5))

cowplot::save_plot(plot = relative_oak_bw,
  base_height = 2.5,
  base_asp = 3,filename =  here("figures", "oak_relinf_white_bw.png"))

```


```{r}
relative_bigcone_bw = ggplot(pinf_plotnew, aes(x = rel.inf, y = Outcome, fill = reorder(var, orderer))) +
  geom_bar(
    stat = "identity", 
    alpha = 0.95, 
    position = "stack", 
    color = "black",       # black outline on bars
    linewidth = 0.3
  ) +
  labs(x = "Relative influence", y = "") +
  scale_fill_manual(
    values = gray.colors(5, start = 0, end = 1),
    name = "Predictor",
    guide = guide_legend(override.aes = list(color = "black", size = 0.5))
  ) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    panel.border = element_blank(),
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    plot.margin = margin(0, 0, 0, 0),
    legend.key = element_rect(color = "black", size = 0.5)
  )
relative_bigcone_bw
cowplot::save_plot(plot = relative_bigcone_bw,
  base_height = 2.5,
  base_asp = 3,filename =  here("figures", "bigcone_relinf_white_bw.png"))

gray_vals <- gray.colors(5, start = 0, end = 1)[c(1, 2, 4, 5)]

relative_oak_bw = ggplot(qinf_plotnew, aes(x = rel.inf, y = Outcome, fill = reorder(var, orderer))) +
  geom_bar(stat = "identity", alpha = 0.95, position = "stack", color = "black") +
  labs(x = "Relative influence", y = "") +
  scale_fill_manual(values = gray_vals,name = "Predictor",
    guide = guide_legend(override.aes = list(color = "black", size = 0.5))) +
  theme_minimal(base_size = 12) +
  theme(
    panel.grid = element_blank(),
    panel.border = element_blank(),
    panel.background = element_rect(fill = NA, color = NA),
    plot.background = element_rect(fill = NA, color = NA),
    plot.margin = margin(0, 0, 0, 0),
    legend.key = element_rect(color = "black", size = 0.5))

cowplot::save_plot(plot = relative_oak_bw,
  base_height = 2.5,
  base_asp = 3,filename =  here("figures", "oak_relinf_white_bw.png"))
```

