---
title: "biomass"
author: "Gabe Runte"
date: "6/30/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(janitor)
library(lubridate)
library(calecopal)
library(tidyverse)
library(dplyr)

gg_soilcolor = scale_color_manual(name = "Soil condition", breaks = c("P", "Q", "C"), 
                                  labels = c("Bigcone", "Oak", "Control"),
                                  values = c("#2A0944", "#3FA796", "#FEC260"))

gg_soilfill = scale_fill_manual(name = "Soil condition", breaks = c("P", "Q", "C"), 
                                  labels = c("Bigcone", "Oak", "Control"),
                                  values = c("#2A0944", "#3FA796", "#FEC260"))
```

```{r, message=FALSE}
seedlings = read_csv(here("data", "seedling_measurements", "seedling_measurements.csv")) %>% 
  clean_names()

wet = read_csv(here("data", "repotting", "ghecto_repotting_destruction.csv")) %>% 
  mutate(correction = wet_below_g/(wet_below_g - wet_tips_g))
dry = read_csv(here("data", "repotting", "ghecto_repotting_dry_biomass.csv")) %>% 
  mutate(seedling_g = bag_with_seedling_g - just_bag_g)

trt = read_csv(here("data", "design", "seedling_treatments.csv"))
repot_scan = read_csv(here("data/repotting", "seedling_scan_data.csv")) %>% 
  select(-seedling_sp, -notes)
```


```{r, message=FALSE}
dry_above = dry  %>% 
  filter(above_below == "A") %>%
  select(seedling_id, seedling_g) %>% 
  rename(dry_above_g = seedling_g)
dry_below = dry  %>% 
  filter(above_below == "B") %>%
  select(seedling_id, seedling_g) %>% 
  rename(dry_below_g = seedling_g)

seedling_treatments = seedlings %>% 
  select(seedling_id, seedling_sp, soil_type)

biomass = left_join(wet, dry_above) %>% 
  left_join(dry_below) %>% 
  mutate(dry_below_corrected = dry_below_g*correction) %>% 
  mutate(total_biomass_g = dry_below_corrected+dry_above_g) %>% 
  left_join(seedling_treatments) %>% 
  mutate(cohort = paste("spp",seedling_sp,"soil",soil_type,sep="" )) %>% 
  mutate(live_soil = 
           case_when(
             soil_type == "C" ~ "No",
             soil_type != "C" ~ "Yes",
           )) %>% 
mutate(above_below = dry_above_g/dry_below_corrected)
```
 
```{r}
ggplot(biomass[biomass$seedling_sp=="Q",], aes(cohort, total_biomass_g)) +
  geom_boxplot(aes(fill = cohort))
ggplot(biomass[biomass$seedling_sp=="P",], aes(cohort, total_biomass_g)) +
  geom_boxplot(aes(fill = cohort))

ggplot(biomass[biomass$seedling_sp=="Q",], aes(cohort, dry_above_g)) +
  geom_boxplot(aes(fill = cohort))
ggplot(biomass[biomass$seedling_sp=="P",], aes(cohort, dry_above_g)) +
  geom_boxplot(aes(fill = cohort))

ggplot(biomass[biomass$seedling_sp=="Q",], aes(cohort, dry_below_corrected)) +
  geom_boxplot(aes(fill = cohort))
ggplot(biomass[biomass$seedling_sp=="P",], aes(cohort, dry_below_corrected)) +
  geom_boxplot(aes(fill = cohort))

ggplot(biomass[biomass$seedling_sp=="Q",], aes(cohort, above_below)) +
  geom_boxplot(aes(fill = cohort))
ggplot(biomass[biomass$seedling_sp=="P",], aes(cohort, above_below)) +
  geom_boxplot(aes(fill = cohort))
```

```{r}
mass = biomass %>% 
  rename(below = dry_below_corrected, above = dry_above_g) %>%
  select(seedling_id, below, above) %>% 
  mutate(total = above+below) %>% 
  mutate(rs_ratio = below/above) %>% 
  left_join(repot_scan) %>% 
  left_join(trt) %>% 
  mutate(total_area = above_area_cm2+underground_area_cm2) %>% 
  mutate(rs_area = underground_area_cm2/above_area_cm2)


ggplot(mass, aes(x = above_area_cm2, y = above, color = soil_type))+
  geom_point()+geom_smooth(method = "lm")+facet_wrap(~seedling_sp, scales = "free")+gg_soilcolor


summary(lm(above~above_area_cm2*seedling_sp, data = mass))
summary(lm(below~underground_area_cm2*seedling_sp, data = mass))
summary(lm(total~sqrt(total_area)*seedling_sp, data = mass))
summary(lm(rs_ratio~rs_area*seedling_sp, data = mass))
```



