---
title: "Size metrics - repotting"
author: "Gabe Runte"
date: "8/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(MASS)
library(tidyverse)
library(here)
library(janitor)
library(lubridate)
library(RColorBrewer)

```


```{r}
#just before repotting
seedling_size = read_csv(here("data", "repotting", "ghecto_repotting_seedling_data.csv")) %>% 
  mutate(timepoint = "3")
t3 = read_csv(here("data", "repotting", "ghecto_repotting_seedling_data.csv")) %>% 
  mutate(timepoint = "3")%>% 
  mutate(month = lubridate::my(032021))

colonization = read_csv(here("data","repotting", "ghecto_repotting_root_pulling_data.csv")) %>% 
  dplyr::select(1:3) %>% 
  mutate(pct_col = colonization_numerator/colonization_denominator)

#from the grow up in year 1 before repotting
seedlings = read_csv(here("data", "seedling_measurements", "seedling_measurements.csv")) %>%
  clean_names()

seedlings = seedlings[(match(unique(seedlings$seedling_id), seedlings$seedling_id)),]%>% 
  dplyr::select(seedling_id, seedling_sp, soil_type)

#first measurements after repotting
post_repotting = read_csv(here("data", "post_repotting_measurements.csv")) %>%
  clean_names() %>% 
  mutate(timepoint = "4")

t4 = post_repotting %>% 
  mutate(month = lubridate::my(042021))

t5 = read_csv(here("data", "seedling_measurements", "seedling_data_timepoint5.csv")) %>%
  clean_names() %>% 
  mutate(timepoint = "5")%>% 
  mutate(month = lubridate::my(122021))

t6 = read_csv(here("data", "seedling_measurements", "seedling_measurements_winter22.csv")) %>%
  clean_names() %>% 
  mutate(timepoint = "6")%>% 
  mutate(month = lubridate::my(022022))

t7 = read_csv(here("data","seedling_measurements", "measurements_april2022.csv")) %>% 
  clean_names() %>% 
  rename(additional_height = add_height)%>% 
  mutate(timepoint = "7")%>% 
  mutate(month = lubridate::my(042022))

t8 = read_csv(here("data", "seedling_measurements", "measurements_jul2022.csv")) %>% 
  clean_names() %>% 
  mutate(timepoint = "8")%>% 
  mutate(month = lubridate::my(082022))

#which seedling was paired with which other seedling? they share a pot number 
potting = read_csv(here("data", "design", "ghecto_neighbor_pairs.csv")) %>% 
  clean_names()

seedling_sizes = t3 %>% 
  bind_rows(t4, t5, t6, t7, t8) 


seedling_size = seedling_sizes %>% 
  left_join(seedlings) 

master_full = seedling_size %>% 
  left_join(potting, by= c("seedling_id" = "seedling_1" )) %>% 
  left_join(potting, by= c("seedling_id" = "seedling_2" )) %>% 
  mutate(pot = case_when(
    !is.na(pot.x) ~ pot.x, 
    !is.na(pot.y) ~ pot.y, 
  )) %>% 
  mutate(neighbor = case_when(
    !is.na(seedling_1) ~ seedling_1, 
    !is.na(seedling_2) ~ seedling_2, 
  )) %>% 
  dplyr::select(!c("pot.x", "pot.y", "seedling_1", "seedling_2")) %>% 
  mutate(total_length = height_cm+ additional_height) %>% 
  left_join(colonization)

all3 = master_full %>% 
  group_by(seedling_id) %>% 
  summarize(n = n()) #%>% 
 # filter(n ==3)

master = master_full #%>% 
  #filter(seedling_id %in% all3$seedling_id)  %>% 
  #mutate(total_length = height_cm + additional_height)

```

```{r}
fj = master_full %>% 
  select(seedling_id, seedling_sp, soil_type) %>% 
  rename(neighbor = seedling_id, n_sp = seedling_sp, n_soil = soil_type)
m = master_full %>% 
  filter(timepoint == 8) %>% 
  left_join(fj) %>% 
  group_by(seedling_sp, soil_type, n_sp, n_soil) %>% 
  summarize(n= n())
  
```


```{r data issues, eval = FALSE}

help = master %>% 
  group_by(seedling_id) %>% 
  summarize(n = n()) %>% 
  filter(n !=3)

problems = master_full %>% 
  filter(is.na(pot))


```


```{r}
#finished 
oaks = seedling_size %>% 
  filter(seedling_sp == "Q")%>% 
  mutate(zheight = (height_cm- mean(height_cm))/sd(height_cm))%>% 
  mutate(zdiameter = (diameter_mm- mean(diameter_mm))/sd(diameter_mm))

bigcone = seedling_size %>% 
  filter(seedling_sp == "P")%>% 
  mutate(zheight = (height_cm- mean(height_cm))/sd(height_cm))%>% 
  mutate(zdiameter = (diameter_mm- mean(diameter_mm))/sd(diameter_mm))%>% 
  filter(height_cm < 10)
```


```{r seedling photos}
photo_data = read_csv(here("data", "seedling_photo_data.csv")) %>% 
  clean_names() %>%
  dplyr::select(!seedling_sp) %>% 
  rename(photo_ht = height_cm) %>%
  dplyr::select(1:5) %>% 
  left_join(seedling_size %>% 
              filter(timepoint ==5)) %>% 
  filter(!is.na(height_cm)) %>% 
  mutate(root_shoot = underground_area_cm2/above_area_cm2)

#remove a bad measure
photo_data = photo_data  %>% 
  filter(seedling_id!=4282)  %>% 
  left_join(colonization)

harvested = read_csv(here("data", "repotting", "ghecto_repotting_dry_biomass.csv")) %>% 
  mutate(mass = bag_with_seedling_g - just_bag_g) %>% 
  mutate(above_below = case_when(
  above_below == "A" ~ "above_dry", 
  above_below == "B" ~ "below_dry"
  )) %>% 
  dplyr::select(seedling_id, above_below, mass) %>% 
  pivot_wider(names_from = above_below, values_from = mass)

harvested_photos = photo_data %>% 
  left_join(harvested) %>% 
  filter(!is.na(above_dry))



```

```{r photo figures}

ggplot(photo_data, aes(x= soil_type,y= above_area_cm2, fill = soil_type )) + 
  geom_boxplot() +
  facet_wrap(~seedling_sp) 


ggplot(photo_data, aes(x= soil_type,y= underground_area_cm2, fill = soil_type )) + 
  geom_boxplot() +
  facet_wrap(~seedling_sp)

ggplot(photo_data, aes(x= soil_type,y= root_shoot, fill = soil_type )) + 
  geom_boxplot() +
  facet_wrap(~seedling_sp) +
  labs(
    y = "Root:Shoot Ratio",
    x= "soil type",
    title = "faceted by Seedling Species"
  )


ggplot(photo_data, aes(x= soil_type,y= above_area_cm2+underground_area_cm2, fill = soil_type )) + 
  geom_boxplot() +
  facet_wrap(~seedling_sp)
```

```{r}

photo_data = photo_data %>% 
  mutate(soil.long = case_when(
             soil_type=="Q"~ "Canyon Oak",
             soil_type=="P"~ "Bigcone",
             soil_type=="C"~ "Control",
           ))
ggplot(photo_data %>% 
         filter(seedling_sp == "P"), aes(x= soil.long,y= above_area_cm2, fill = soil.long )) + 
  geom_boxplot(alpha = 0.8)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(title = "Bigcone aboveground area",
       y= "Aboveground area (cm2)") +
  geom_jitter(width = .3, alpha = 0.35, aes(color = soil.long))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))

ggplot(photo_data %>% 
         filter(seedling_sp == "Q"), aes(x= soil.long,y= above_area_cm2, fill = soil.long )) + 
  geom_boxplot(alpha = 0.8)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(title = "Bigcone aboveground area",
       y= "Aboveground area (cm2)") +
  geom_jitter(width = .3, alpha = 0.35, aes(color = soil.long))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))

#ggsave(here("figures", "t1_bigcone_size.pdf"), height = 5, width = 7)

ggplot(photo_data %>% 
         filter(seedling_sp == "Q"), aes(x= soil_type,y= above_area_cm2, fill = soil.long )) + 
  geom_boxplot()+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(title = "Canyon oak aboveground area",
       y= "Aboveground area (cm2)")
ggsave(here("figures", "t1_oak_size.pdf"))


TukeyHSD(aov(lm(root_shoot~soil_type, data = photo_data %>% 
         filter(seedling_sp == "P"))))

TukeyHSD(aov(lm(root_shoot~soil_type, data = photo_data %>% 
         filter(seedling_sp == "Q"))))

#TukeyHSD(aov(lm(above_area_cm2~soil_type, data = photo_data %>% 
       #  filter(seedling_sp == "P"))))

TukeyHSD(aov(lm(above_area_cm2~soil_type, data = photo_data %>% 
         filter(seedling_sp == "Q"))))

#TukeyHSD(aov(lm((above_area_cm2+underground_area_cm2)~soil_type, data = photo_data %>% 
       #  filter(seedling_sp == "P"))))

TukeyHSD(aov(lm((above_area_cm2+underground_area_cm2)~soil_type, data = photo_data %>% 
         filter(seedling_sp == "Q"))))

ggplot(photo_data %>% 
         filter(seedling_sp == "P"), aes(x= soil_type,y= root_shoot, fill = soil.long )) + 
  geom_boxplot()+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(title = "Bigcone root:shoot ratio",
       y= "Root:shoot ratio")+geom_jitter(width = .3, alpha = 0.35, aes(color = soil.long))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))
ggsave(here("figures", "t1_bigcone_rootshoot.pdf"), width = 7, height = 5)

ggplot(photo_data %>% 
         filter(seedling_sp == "Q"), aes(x= soil_type,y= root_shoot, fill = soil.long )) + 
  geom_boxplot()+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(title = "Canyon oak root:shoot ratio",
       y= "Root:shoot ratio")
ggsave(here("figures", "t1_oak_rootshoot.pdf"))



ggplot(photo_data %>% 
         filter(seedling_sp == "P"), aes(x= pct_col,y= above_area_cm2, color = soil.long )) + 
  geom_point()+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal() +
  labs(x= "Percent Colonization",
       y = "Aboveground area (cm2)")
ggsave(here("figures", "bigcone_area_tocol.pdf"))


ggplot(photo_data %>% 
         filter(seedling_sp == "P"), aes(x= pct_col,y= root_shoot, color = soil_type )) + 
  geom_point()+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal() +
  labs(x= "Percent Colonization",
       y = "Root:shoot ratio")
ggsave(here("figures", "bigcone_rootshoot_tocol.pdf"))

```


```{r}
photo_data = photo_data %>%
  mutate(total_area = above_area_cm2+underground_area_cm2)

dest_mass = read_csv(here("data", "repotting", "ghecto_repotting_dry_biomass.csv")) %>% 
  mutate(mass = bag_with_seedling_g + just_bag_g) %>% 
  mutate(above_below = 
           case_when(
             above_below == "A" ~"above_mass", 
             above_below == "B" ~"below_mass"
           )) %>% 
  dplyr::select(seedling_id, above_below, mass) %>% 
  pivot_wider(values_from = mass,names_from = above_below) %>% 
  mutate(total_mass = above_mass+below_mass)

photo_dest = photo_data %>% 
  left_join(dest_mass) %>% 
  dplyr::filter(!is.na(total_mass))

ggplot(photo_data, aes(x= photo_ht, y= height_cm)) +
  geom_point(aes(color= seedling_sp))

summary(lm(photo_ht~height_cm, data= photo_data))
```

```{r}
photo_lm = lm(root_shoot~seedling_sp*soil_type, data = photo_data)
summary(photo_lm)
anova(photo_lm)
TukeyHSD(aov(photo_lm))

photo_lm2 = lm(above_area_cm2~seedling_sp*soil_type, data = photo_data)
summary(photo_lm2)
anova(photo_lm2)
TukeyHSD(aov(photo_lm2))

photo_lm3 = lm(underground_area_cm2~seedling_sp*soil_type, data = photo_data)
summary(photo_lm3)
anova(photo_lm3)
TukeyHSD(aov(photo_lm3))

summary(photo_lm)$r.squared
summary(photo_lm2)$r.squared
summary(photo_lm3)$r.squared
```

```{r}
oak_lm = lm(root_shoot~soil_type, data = photo_data %>% 
              filter(seedling_sp=="Q"))
summary(oak_lm)
anova(oak_lm)
TukeyHSD(aov(oak_lm))

oak_lm2 = lm(above_area_cm2~soil_type, data = photo_data %>% 
              filter(seedling_sp=="Q"))
summary(oak_lm2)
anova(oak_lm2)
TukeyHSD(aov(oak_lm2))

oak_lm3 = lm(underground_area_cm2~soil_type, data = photo_data %>% 
              filter(seedling_sp=="Q"))
summary(oak_lm3)
anova(oak_lm3)
TukeyHSD(aov(oak_lm3))

summary(oak_lm)$r.squared
summary(oak_lm2)$r.squared
summary(oak_lm3)$r.squared
```

```{r}
pine_lm = lm(root_shoot~soil_type, data = photo_data %>% 
              filter(seedling_sp=="P"))
summary(pine_lm)
anova(pine_lm)
TukeyHSD(aov(pine_lm))

pine_lm2 = lm(above_area_cm2~soil_type, data = photo_data %>% 
              filter(seedling_sp=="P"))
summary(pine_lm2)
anova(pine_lm2)
TukeyHSD(aov(pine_lm2))

pine_lm3 = lm(underground_area_cm2~soil_type, data = photo_data %>% 
              filter(seedling_sp=="P"))
summary(pine_lm3)
anova(pine_lm3)
TukeyHSD(aov(pine_lm3))


summary(pine_lm)$r.squared
summary(pine_lm2)$r.squared
summary(pine_lm3)$r.squared
```

```{r}
neighbor.facts = master %>% 
  filter(timepoint == 4)   %>% 
  dplyr::select("seedling_id", "height_cm", "diameter_mm", "seedling_sp", "soil_type") %>% 
  rename(neighbor = seedling_id, 
         neighb.height = height_cm, 
         neighb.diameter = diameter_mm, 
         neighb.spp = seedling_sp, 
         neighb.soil = soil_type)

master4 = master %>% 
  filter(timepoint ==4) %>% 
  left_join(neighbor.facts, by = "neighbor") %>% 
  filter(!is.na(neighb.height))


master4 = master4 %>% 
  left_join(master %>% 
            filter(timepoint==4) %>% 
            dplyr::select("seedling_id", "height_cm", "diameter_mm", "chlorosis", "leaf_count")%>%
            rename(lastheight = height_cm, 
                   lastdiameter = diameter_mm, 
                   lastchlorosis = chlorosis, 
                   lastleaf = leaf_count)
              )%>% 
  mutate(change.ht = height_cm - lastheight, 
         change.dia = diameter_mm - lastdiameter,
         change.chl = chlorosis - lastchlorosis,
         change.leaf = leaf_count - lastleaf
         ) %>% 
  filter(change.ht > -10)

```

```{r}
neighbor5 = master %>% 
  filter(timepoint == 5)   %>% 
  dplyr::select("seedling_id", "height_cm", "diameter_mm", "seedling_sp", "soil_type") %>% 
  rename(neighbor = seedling_id, 
         neighb.height = height_cm, 
         neighb.diameter = diameter_mm, 
         neighb.spp = seedling_sp, 
         neighb.soil = soil_type)

master5 = master %>% 
  filter(timepoint ==5) %>% 
  left_join(neighbor.facts, by = "neighbor") %>% 
  filter(!is.na(neighb.height))

master5 = master5 %>% 
  left_join(master %>% 
            filter(timepoint==4) %>% 
            dplyr::select("seedling_id", "height_cm", "diameter_mm", "chlorosis", "leaf_count")%>%
            rename(lastheight = height_cm, 
                   lastdiameter = diameter_mm, 
                   lastchlorosis = chlorosis, 
                   lastleaf = leaf_count)
              )%>% 
  mutate(change.ht = height_cm - lastheight, 
         change.dia = diameter_mm - lastdiameter,
         change.chl = chlorosis - lastchlorosis,
         change.leaf = leaf_count - lastleaf
         ) %>% 
  filter(change.ht > -10)

```

```{r Feb 2022}
master6 = master %>% 
  filter(timepoint ==6)  %>% 
  left_join(master %>% 
            filter(timepoint==4) %>% 
            dplyr::select("seedling_id", "height_cm", "diameter_mm", "chlorosis", "leaf_count")%>%
            rename(initialheight = height_cm, 
                   initialdiameter = diameter_mm, 
                   initialchlorosis = chlorosis, 
                   initialleaf = leaf_count)
              )%>% 
  mutate(change.ht = height_cm - initialheight, 
         change.dia = diameter_mm - initialdiameter,
         change.chl = chlorosis - initialchlorosis,
         change.leaf = leaf_count - initialleaf,
         change.length = total_length - initialheight
         )  

neighbor6 = master6   %>% 
  dplyr::select(seedling_id, height_cm, diameter_mm, seedling_sp, soil_type, 
                change.ht, change.dia, change.chl, change.leaf, change.length) %>% 
  rename(neighbor = seedling_id, 
         neighb.height = height_cm, 
         neighb.diameter = diameter_mm, 
         neighb.spp = seedling_sp, 
         neighb.soil = soil_type, 
         neighb.change.ht = change.ht,
         neighb.change.dia = change.dia, 
         neighb.change.chl = change.chl,
         neighb.change.leaf = change.leaf, 
         neighb.change.length = change.length)

master6 = master6 %>% 
  left_join(neighbor6)
```

```{r April 2022}
master7 = master %>% 
  filter(timepoint ==7)  %>% 
  left_join(master %>% 
            filter(timepoint==4) %>% 
            dplyr::select("seedling_id", "height_cm", "diameter_mm", "chlorosis", "leaf_count")%>%
            rename(initialheight = height_cm, 
                   initialdiameter = diameter_mm, 
                   initialchlorosis = chlorosis, 
                   initialleaf = leaf_count)
              )%>% 
  mutate(change.ht = height_cm - initialheight, 
         change.dia = diameter_mm - initialdiameter,
         change.chl = chlorosis - initialchlorosis,
         change.leaf = leaf_count - initialleaf,
         change.length = total_length - initialheight
         )  

neighbor7 = master7   %>% 
  dplyr::select(seedling_id, height_cm, diameter_mm, seedling_sp, soil_type, 
                change.ht, change.dia, change.chl, change.leaf, change.length) %>% 
  rename(neighbor = seedling_id, 
         neighb.height = height_cm, 
         neighb.diameter = diameter_mm, 
         neighb.spp = seedling_sp, 
         neighb.soil = soil_type, 
         neighb.change.ht = change.ht,
         neighb.change.dia = change.dia, 
         neighb.change.chl = change.chl,
         neighb.change.leaf = change.leaf, 
         neighb.change.length = change.length)

master7 = master7 %>% 
  left_join(neighbor7) %>% 
  mutate(is.ecto = soil_type %in% c("P", "Q")) %>% 
  mutate(neighb.ecto = neighb.soil %in% c("P", "Q"))
```




```{r relative growth}
m7 = master7 %>% 
  filter(!is.na(change.ht)) %>% 
  mutate(spp_long = 
           case_when(
             seedling_sp=="Q"~ "Oak seedling",
             seedling_sp=="P"~ "Bigcone seedling",
           )) %>% 
    mutate(soil_long = 
           case_when(
             soil_type=="Q"~ "Oak soil",
             soil_type=="P"~ "Bigcone soil",
             soil_type=="C"~ "Control soil",
           )) %>% 
  mutate(n_sp_long = 
           case_when(
             neighb.spp=="Q"~ "Oak neighbor",
             neighb.spp=="P"~ "Bigcone neighbor",
           )) %>% 
  mutate(n_soil_long = 
           case_when(
             neighb.soil=="Q"~ "Neighbor soil Oak",
             neighb.soil=="P"~ "Neighbor soil Bigcone",
             neighb.soil=="C"~ "Neighbor soil Control",
           ))  %>% 
  filter(!is.na(n_soil_long))%>% 
  filter(!is.na(soil_long)) %>% 
  mutate(rel.growth = change.length/initialheight) %>% 
  mutate(comp_growth = change.length/neighb.change.length)


oaks = m7 %>% 
  filter(seedling_sp== "Q")
bigcone = m7 %>% 
  filter(seedling_sp == "P")




growth.7 = m7 %>% 
  group_by(seedling_sp) %>% 
  mutate(rel_change_ht = (change.ht-mean(change.ht))/sd(change.ht))%>% 
  mutate(rel_change_dia = (change.dia-mean(change.dia))/sd(change.dia))

ggplot(growth.7, aes(neighb.spp, rel_change_ht, fill = neighb.soil)) + 
  geom_boxplot() +
  facet_grid(rows = vars(seedling_sp), cols = vars(soil_type))

ggplot(growth.7, aes( soil_type, rel_change_dia, fill = neighb.spp)) + 
  geom_boxplot() +
  facet_wrap(~seedling_sp)


ggplot(growth.7, aes())
```

```{r}
ggplot(bigcone, aes(y = total_length, x = soil_long, fill = soil_long, color= soil_long)) +
  geom_boxplot(alpha = .5) +
  geom_jitter(alpha = .5, width = .25) +
  labs(
    y = "Total Length",
    x = "Soil Type",
    color = "Soil type",
    fill = "Soil type"
  )
ggplot(oaks, aes(y = total_length, x = soil_long, fill = soil_long, color= soil_long)) +
  geom_boxplot(alpha = .5) +
  geom_jitter(alpha = .5, width = .25) +
  labs(
    y = "Total Length",
    x = "Soil Type",
    color = "Soil type",
    fill = "Soil type"
  )
ggplot(oaks, aes(y = change.leaf, x = n_soil_long, fill = n_soil_long, color= n_soil_long)) +
  geom_boxplot(alpha = .5) +
  geom_jitter(alpha = .5, width = .25) +
  facet_grid(rows=vars(n_sp_long), cols = vars(soil_long )) +
  labs(
    y = "Change in Health",
    x = "Neighbor Soil Type",
    color = "Neighbor Soil",
    fill = "Neighbor Soil"
  )

ggplot(bigcone, aes(y= change.chl, x = soil_type, fill = n_soil_long))  +
  geom_boxplot(alpha = .5)  +
  facet_grid(rows=vars(n_sp_long), cols = vars(soil_long )) +
  labs(
    y = "Relative Growth",
    x = "Neighbor Soil Type",
    color = "Neighbor Soil",
    fill = "Neighbor Soil"
  )
  
  
  ggplot(master7) +
    geom_boxplot(aes(x = neighb.soil, y = change.length, fill = neighb.spp)) +
    facet_wrap(~seedling_sp)
  
    ggplot(master7) +
    geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.spp)) +
    facet_wrap(~seedling_sp)
    
    ggplot(bigcone) +
    geom_boxplot(aes(x = neighb.ecto, y = change.length, fill = neighb.ecto)) +
      facet_wrap(~neighb.spp)
    
ggplot(bigcone) +
  geom_boxplot(aes(x = neighb.soil, y = change.length, fill = neighb.spp)) +
  facet_wrap(~soil_type)

    
ggplot(bigcone) +
  geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.soil)) +
  facet_wrap(~soil_type)

    
ggplot(oaks) +
  geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.soil)) +
  facet_wrap(~soil_type)


ggplot(oaks) +
  geom_boxplot(aes(x = neighb.soil, y = change.length, fill = neighb.spp)) +
  facet_wrap(~soil_type)
    

ggplot(bigcone) +
  geom_boxplot(aes(x = soil_type, y = change.chl, fill = neighb.spp)) +
  facet_wrap(~neighb.soil)


wilcox.test(bigcone$change.dia~bigcone$neighb.spp)
wilcox.test(bigcone$change.length~bigcone$neighb.ecto)
wilcox.test(oaks$change.length~oaks$neighb.spp)

TukeyHSD(aov(lm(change.length~seedling_sp*soil_type*neighb.spp*neighb.soil, data = m7)))
```


```{r}

master7 = master7 %>% 
  mutate(seedling_sp = recode(seedling_sp, "P" = "Bigcone", "Q" = "Canyon Oak"))%>% 
  mutate(neighb.soil = recode(neighb.soil, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  mutate(soil_type = recode(soil_type, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  filter(!pot %in% c(211211, 211298))



ggplot(master7) +
    geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.spp)) +
    facet_wrap(~seedling_sp)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2"), name = "Neighbor species",
    breaks = c("P", "Q"), labels = c("Bigcone", "Canyon Oak"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(x = "Neighbor Species",
       y= "Growth since repotting")

#ggsave(here("figures", "growth_both.pdf"))
    

ggplot(master7) +
    geom_boxplot(aes(x = neighb.soil, y = change.length, fill = neighb.spp)) +
    facet_wrap(~seedling_sp)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2"), name = "Neighbor species",
    breaks = c("P", "Q"), labels = c("Bigcone", "Canyon Oak"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(x = "Soil Type",
       y= "Growth since repotting")
  
 # ggsave(here("figures", "growth_both_bysoil.pdf"))
  bigcone1 = bigcone %>% 
  mutate(seedling_sp = recode(seedling_sp, "P" = "Bigcone", "Q" = "Canyon Oak"))%>% 
  mutate(neighb.soil = recode(neighb.soil, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  mutate(soil_type = recode(soil_type, "P" = "Bigcone soil", "Q" = "Canyon Oak soil", "C" = "Control soil")) %>% 
  mutate(neighb.spp = recode(neighb.spp, "P" = "Bigcone", "Q" = "Canyon Oak"))

  
  oaks1 = oaks %>% 
  mutate(seedling_sp = recode(seedling_sp, "P" = "Bigcone", "Q" = "Canyon Oak"))%>% 
  mutate(neighb.soil = recode(neighb.soil, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  mutate(soil_type = recode(soil_type, "P" = "Bigcone soil", "Q" = "Canyon Oak soil", "C" = "Control soil")) %>% 
  mutate(neighb.spp = recode(neighb.spp, "P" = "Bigcone", "Q" = "Canyon Oak"))
  
ggplot(bigcone1) +
  geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.soil)) +
  facet_wrap(~soil_type)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
  labs(title = "Bigcone Growth",
       x = "Neighbor Species",
       y= "Growth since repotting")
ggsave(here("figures", "growth_bigcone_crossed.pdf"), height = 7, width = 7)
    
ggplot(oaks1) +
  geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.soil)) +
  facet_wrap(~soil_type)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
  labs(title = "Canyon Oak Growth",
       x = "Neighbor Species",
       y= "Growth since repotting")
ggsave(here("figures", "growth_oaks_crossed.pdf"), height = 7, width = 7)

#########

ggplot(master7 %>% 
         filter(soil_type == "Control") %>% 
         filter(seedling_sp == "Bigcone"), aes(x = neighb.soil, y = change.length
, fill = neighb.soil)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(x = "Soil Type",
       y= "Growth since repotting")+
  geom_jitter(width = .3, alpha = 0.35, aes(color = neighb.soil))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))

ggsave(here("figures", "t1_bigcone_size.pdf"), height = 5, width = 5)

```


```{r, eval = FALSE}
scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(title = "Canyon oak aboveground area",
       y= "Aboveground area (cm2)")
```


```{r}
lm1 = lm(change.length~seedling_sp*soil_type*neighb.spp*neighb.soil, data = master7)

lm2 = lm(change.length~soil_type+neighb.spp*neighb.soil, data = bigcone)


lm3 = lm(change.length~soil_type+neighb.spp*neighb.soil, data = oaks)

TukeyHSD(aov(lm1))
TukeyHSD(aov(lm2))
TukeyHSD(aov(lm3))

plot(lm2)
plot(lm3)
```



```{r}
woah = growth.6 %>% 
  group_by(seedling_sp, soil_type, neighb.spp,neighb.soil) %>% 
  summarize(growth = mean(rel_change_ht),
            sd = sd(rel_change_ht),
            real.growth = mean(change.ht))
```


```{r}
ggplot(m6, aes(x= soil_long, y=change.ht)) +
  geom_boxplot(aes(fill = n_sp_long)) +
  facet_grid(rows=vars(spp_long), cols = vars(n_soil_long))

ggplot(m6 %>% filter(seedling_sp=="P"), aes(x= soil_long, y=change.length, fill = n_soil_long)) +
  geom_boxplot() +
  facet_grid(rows=vars(n_sp_long))
  

ggplot(m6, aes(x= soil_long, y=change.length)) +
  geom_boxplot(aes(fill = n_sp_long)) +
  facet_grid(rows=vars(spp_long))

ggplot(m6, aes(x= soil_long, y=change.ht, color = n_sp_long, fill = n_sp_long), group = n_sp_long) +
  geom_boxplot(alpha = .5) +
  geom_jitter(alpha = .5, width = .25) +
  facet_grid(rows=vars(spp_long), cols = vars(n_sp_long ))
```





```{r}



ggplot(oaks, aes(x=soil_type, y=height_cm, fill= soil_type)) +
  geom_boxplot()+
  facet_wrap(~timepoint) +
  labs(title = "Oak height")

ggplot(oaks, aes(x=soil_type, y=diameter_mm, fill= soil_type)) +
  geom_boxplot()+
  facet_wrap(~timepoint) +
  labs(title = "Oak diameter")

##################

ggplot(bigcone, aes(x=soil_type, y=height_cm, fill= soil_type)) +
  geom_boxplot()+
  facet_wrap(~timepoint) +
  labs(title = "Bigcone height")

ggplot(bigcone, aes(x=timepoint, y=diameter_mm, fill= soil_type)) +
  geom_boxplot() +
  facet_wrap(~soil_type) +
  labs(title = "Bigcone diameter")

ggplot(oaks, aes(x=timepoint, y=diameter_mm, fill= soil_type)) +
  geom_boxplot() +
  facet_wrap(~soil_type) +
  labs(title = "Bigcone diameter")


```











```{r}
ggplot(m7 %>% 
         filter(seedling_sp == "P"), aes(soil_type, change.length, fill = soil_type)) +
  geom_boxplot()
plot(lm(log(total_length)~soil_type, data = m7 %>% filter(seedling_sp == "P")))
TukeyHSD(aov(lm(log(total_length)~soil_type, data = m7 %>% filter(seedling_sp == "P"))))

ggplot(m7 %>% 
         filter(seedling_sp == "Q"), aes(soil_type, log(total_length), fill = soil_type)) +
  geom_boxplot()


plot(lm(log(total_length)~soil_type, data = m7 %>% filter(seedling_sp == "Q")))
TukeyHSD(aov(lm(log(total_length)~soil_type, data = m7 %>% filter(seedling_sp == "Q"))))

ggplot(m7 %>% 
         filter(seedling_sp == "P"), aes(soil_type, change.dia, fill = soil_type)) +
  geom_boxplot()

ggplot(m7 %>% 
         filter(seedling_sp == "Q"), aes(soil_type, change.dia, fill = soil_type)) +
  geom_boxplot()



```



```{r April 2022}
master8 = master %>% 
  filter(timepoint ==8)  %>% 
  left_join(master %>% 
            filter(timepoint==4) %>% 
            dplyr::select("seedling_id", "height_cm", "diameter_mm", "chlorosis", "leaf_count")%>%
            rename(initialheight = height_cm, 
                   initialdiameter = diameter_mm, 
                   initialchlorosis = chlorosis, 
                   initialleaf = leaf_count)
              )%>% 
  mutate(change.ht = height_cm - initialheight, 
         change.dia = diameter_mm - initialdiameter,
         change.chl = chlorosis - initialchlorosis,
         change.leaf = leaf_count - initialleaf,
         change.length = total_length - initialheight
         )  

neighbor8 = master8   %>% 
  dplyr::select(seedling_id, height_cm, diameter_mm, seedling_sp, soil_type, 
                change.ht, change.dia, change.chl, change.leaf, change.length) %>% 
  rename(neighbor = seedling_id, 
         neighb.height = height_cm, 
         neighb.diameter = diameter_mm, 
         neighb.spp = seedling_sp, 
         neighb.soil = soil_type, 
         neighb.change.ht = change.ht,
         neighb.change.dia = change.dia, 
         neighb.change.chl = change.chl,
         neighb.change.leaf = change.leaf, 
         neighb.change.length = change.length)

master8 = master8 %>% 
  left_join(neighbor8) %>% 
  mutate(is.ecto = soil_type %in% c("P", "Q")) %>% 
  mutate(neighb.ecto = neighb.soil %in% c("P", "Q"))

summarize(master8 %>% 
            group_by(seedling_sp, soil_type, neighb.soil, neighb.spp),
          n = n())
```




```{r relative growth}
m8 = master8 %>% 
  filter(!is.na(change.ht)) %>% 
  mutate(spp_long = 
           case_when(
             seedling_sp=="Q"~ "Oak seedling",
             seedling_sp=="P"~ "Bigcone seedling",
           )) %>% 
    mutate(soil_long = 
           case_when(
             soil_type=="Q"~ "Oak soil",
             soil_type=="P"~ "Bigcone soil",
             soil_type=="C"~ "Control soil",
           )) %>% 
  mutate(n_sp_long = 
           case_when(
             neighb.spp=="Q"~ "Oak neighbor",
             neighb.spp=="P"~ "Bigcone neighbor",
           )) %>% 
  mutate(n_soil_long = 
           case_when(
             neighb.soil=="Q"~ "Neighbor soil Oak",
             neighb.soil=="P"~ "Neighbor soil Bigcone",
             neighb.soil=="C"~ "Neighbor soil Control",
           ))  %>% 
  filter(!is.na(n_soil_long))%>% 
  filter(!is.na(soil_long)) %>% 
  mutate(rel.growth = change.length/initialheight) %>% 
  mutate(comp_growth = change.length/neighb.change.length)


oaks = m8 %>% 
  filter(seedling_sp== "Q")
bigcone = m8 %>% 
  filter(seedling_sp == "P") 

bc_real = bigcone %>% 
  filter(comp_growth < 86)

oaks_real = oaks %>% 
  filter(comp_growth < 86)


growth.8 = m8 %>% 
  group_by(seedling_sp) %>% 
  mutate(rel_change_ht = (change.ht-mean(change.ht))/sd(change.ht))%>% 
  mutate(rel_change_dia = (change.dia-mean(change.dia))/sd(change.dia))

ggplot(growth.8, aes(neighb.spp, rel_change_ht, fill = neighb.soil)) + 
  geom_boxplot() +
  facet_grid(rows = vars(seedling_sp), cols = vars(soil_type))

ggplot(growth.8, aes( soil_type, rel_change_dia, fill = neighb.spp)) + 
  geom_boxplot() +
  facet_wrap(~seedling_sp)


ggplot(oaks, aes(x = soil_type, y= change.length,fill = neighb.soil )) +
  geom_boxplot()

ggplot(oaks, aes(x = soil_type, y= comp_growth,fill = neighb.soil )) +
  geom_boxplot()

ggplot(bigcone, aes(x = soil_type, y= comp_growth,fill = neighb.soil )) +
  geom_boxplot()

TukeyHSD(aov(change.length~neighb.soil, data = oaks_real %>% 
               filter(soil_type == "C")))

TukeyHSD(aov(change.length~neighb.soil, data = bc_real %>% 
               filter(soil_type == "C")))

TukeyHSD(aov(change.length~neighb.soil, data = oaks_real %>% 
               filter(soil_type == "Q")))

TukeyHSD(aov(change.length~neighb.soil, data = bc_real %>% 
               filter(soil_type == "Q")))

TukeyHSD(aov(change.length~neighb.soil, data = oaks_real %>% 
               filter(soil_type == "P")))

TukeyHSD(aov(change.length~neighb.soil, data = bc_real %>% 
               filter(soil_type == "P")))

#########

TukeyHSD(aov(change.length~neighb.spp*neighb.soil, data = oaks_real %>% 
               filter(soil_type == "Q")))

TukeyHSD(aov(change.length~neighb.spp*neighb.soil, data = bc_real %>% 
               filter(soil_type == "Q")))

TukeyHSD(aov(change.length~neighb.spp*neighb.soil, data = oaks_real %>% 
               filter(soil_type == "P")))

TukeyHSD(aov(change.length~neighb.spp*neighb.soil, data = bc_real %>% 
               filter(soil_type == "P")))
```

```{r}
master8 = master8 %>% 
  mutate(seedling_sp = recode(seedling_sp, "P" = "Bigcone", "Q" = "Canyon Oak"))%>% 
  mutate(neighb.soil = recode(neighb.soil, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  mutate(soil_type = recode(soil_type, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  filter(!is.na(neighb.soil)) %>% 
  filter(pct_col <1)



ggplot(master8) +
    geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.spp)) +
    facet_wrap(~seedling_sp)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2"), name = "Neighbor species",
    breaks = c("P", "Q"), labels = c("Bigcone", "Canyon Oak"))+
  theme_minimal()+
     theme(axis.title.x = element_blank(), axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  labs(x = "Neighbor Species",
       y= "Growth since repotting")

#ggsave(here("figures", "growth_both.pdf"))
    

ggplot(master8) +
    geom_boxplot(aes(x = neighb.soil, y = change.length, fill = neighb.spp)) +
    facet_wrap(~seedling_sp)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2"), name = "Neighbor species",
    breaks = c("P", "Q"), labels = c("Bigcone", "Canyon Oak"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(x = "Soil Type",
       y= "Growth since repotting")
  
 # ggsave(here("figures", "growth_both_bysoil.pdf"))
  bigcone1 = bigcone %>% 
  mutate(seedling_sp = recode(seedling_sp, "P" = "Bigcone", "Q" = "Canyon Oak"))%>% 
  mutate(neighb.soil = recode(neighb.soil, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  mutate(soil_type = recode(soil_type, "P" = "Bigcone soil", "Q" = "Canyon Oak soil", "C" = "Control soil")) %>% 
  mutate(neighb.spp = recode(neighb.spp, "P" = "Bigcone", "Q" = "Canyon Oak"))

  
  oaks1 = oaks %>% 
  mutate(seedling_sp = recode(seedling_sp, "P" = "Bigcone", "Q" = "Canyon Oak"))%>% 
  mutate(neighb.soil = recode(neighb.soil, "P" = "Bigcone", "Q" = "Canyon Oak", "C" = "Control")) %>% 
  mutate(soil_type = recode(soil_type, "P" = "Bigcone soil", "Q" = "Canyon Oak soil", "C" = "Control soil")) %>% 
  mutate(neighb.spp = recode(neighb.spp, "P" = "Bigcone", "Q" = "Canyon Oak"))
  
ggplot(bigcone1) +
  geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.soil)) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
  labs(title = "Bigcone Growth",
       x = "Neighbor Species",
       y= "Growth since repotting")
#ggsave(here("figures", "growth_bigcone_crossed.pdf"), height = 7, width = 7)
    
ggplot(oaks1) +
  geom_boxplot(aes(x = neighb.spp, y = change.length, fill = neighb.soil)) +
  facet_wrap(~soil_type)+
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
  labs(title = "Canyon Oak Growth",
       x = "Neighbor Species",
       y= "Growth since repotting")
#ggsave(here("figures", "growth_oaks_crossed.pdf"), height = 7, width = 7)
```


```{r}
#########

ggplot(master8 %>% 
         filter(soil_type == "Control")%>% 
         filter(seedling_sp == "Bigcone"),aes(x = neighb.soil, y = change.length, fill = neighb.soil, color = neighb.soil)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Neighbor Soil",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(x = "Neighbor Soil Type",
       y= "Growth since repotting") +
  geom_jitter(alpha = .35, width = .3)
#ggsave(here("figures", "bigcone_growthsincerepotting.jpg"), height = 5, width = 7)

TukeyHSD(aov(lm(change.length~neighb.soil, data = master8 %>% 
         filter(soil_type == "Control")%>% 
         filter(seedling_sp == "Bigcone"))
      ))


master8.1 = master8 %>% 
  mutate(soil_type = fct_relevel(master8$soil_type, c("Control", "Bigcone", "Canyon Oak")))

ggplot(master8.1 %>% 
         dplyr::filter(seedling_sp == "Bigcone"), 
       aes(x = soil_type, y = pct_col, fill = soil_type, color = soil_type)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("Bigcone", "Canyon Oak", "Control"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(x = "Soil Type",
       y= "Percent colonized root tips") +
  geom_jitter(alpha = .35, width = .3)

#ggsave(here("figures", "bigcone_colonization.jpg"), height = 7, width = 7)




summarize(master8 %>% 
            group_by(seedling_sp, soil_type, neighb.spp, neighb.soil), 
          n = n())
  


```
```{r}


ggplot(photo_data %>% 
         filter(seedling_sp=="Q"),aes(x = soil_type, y = height_cm, fill = soil_type, color = soil_type)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(title = "Oaks",
       x = "Soil Type",
       y= "Seedling Size at First Harvest") +
  geom_jitter(alpha = .35, width = .3)
#ggsave(here("figures", "repotting_oak_height.jpg"))
ggplot(photo_data %>% 
         filter(seedling_sp=="P"),aes(x = soil_type, y = height_cm, fill = soil_type, color = soil_type)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(title = "Bigcones",
         x = "Soil Type",
       y= "Seedling Size at First Harvest") +
  geom_jitter(alpha = .35, width = .3)

#ggsave(here("figures", "repotting_bigcone_height.jpg"))


TukeyHSD(aov(lm(underground_area_cm2/above_area_cm2~soil_type, data = photo_data %>% 
         filter(seedling_sp == "P"))
      ))

TukeyHSD(aov(lm(underground_area_cm2/above_area_cm2~soil_type, data = photo_data %>% 
         filter(seedling_sp == "Q"))
      ))

ggplot(photo_data %>% 
         filter(seedling_sp=="Q"),aes(x = soil_type, y = underground_area_cm2/above_area_cm2, fill = soil_type, color = soil_type)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(title = "Oaks",
       x = "Soil Type",
       y= "Root:Shoot at First Harvest") +
  geom_jitter(alpha = .35, width = .3)
#ggsave(here("figures", "repotting_oak_rootshoot.jpg"))
ggplot(photo_data %>% 
         filter(seedling_sp=="P"),aes(x = soil_type, y = underground_area_cm2/above_area_cm2, fill = soil_type, color = soil_type)) +
    geom_boxplot(alpha = 0.75) +
  scale_fill_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  scale_color_manual(
    values = c("darkseagreen4", "darkgoldenrod2", "cadetblue3" ), name = "Soil Type",
    breaks = c("P", "Q", "C"), labels = c("Bigcone", "Canyon Oak", "Control"))+
  theme_minimal()+
     theme(axis.ticks.x=element_blank())+
  labs(title = "Bigcones",
         x = "Soil Type",
       y= "Root:Shoot at First Harvest") +
  geom_jitter(alpha = .35, width = .3)

#ggsave(here("figures", "repotting_bigcone_rootshoot.jpg"))
```

