---
title: "Untitled"
author: "Gabe Runte"
date: "2024-06-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(janitor)
library(RColorBrewer)
library(kableExtra)
library(tidyverse)

source(here("src", "colors.R"))
```

## Read in files
```{r, message = F}
measure = read_csv(here("data", "analysis/size_master.csv"))
harvest = read_csv(here("data", "analysis/harvest_metrics.csv")) 
health = read_csv(here("data", "analysis/ndvi_data.csv"))
harvest_tips = read_csv(here("data", "analysis/harvest_roottips - all.csv")) %>% 
  filter(!is.na(seedling_id))
repot_tips = read_csv(here("data", "repotting/ghecto_repotting_root_pulling_data.csv"))
harvest_mass = read_csv(here("data", "harvest", "harvest_biomass_wideclean.csv"))
image_data = read_csv(here("data", "wide_final_seedling_area.csv"))
repot_mass = read_csv(here("data", "repotting", "repotting_drymass_fitted.csv"))
neighb_pairs = read_csv(here("data", "design", "ghecto_neighbor_pairs.csv"))
trt = read_csv(here("data", "design", "seedling_treatments.csv"))
drought = read_csv(here("data", "design", "drought_assignments_bypot.csv")) %>% select(1,3)
harvest_comm = read_csv( here("data", "harvest", "harvest_community_matrix_scaled.csv"))

pressure = read_csv(here("data/harvest", "pressure_bomb - Sheet1.csv")) %>% select(1:4) %>%  mutate(time = tolower(time))
sapwood = read_csv(here("data/harvest", "harvest_sapwood.csv"))

ndvi_mean = health %>% 
  group_by(seedling_id) %>% 
  summarize(ndvi = mean(mean_ndvi))
```

### Edit/compile some files
```{r, warning = F, message=F}
colonization = repot_tips %>% 
  mutate(repot_col = case_when(
    colonization_numerator == 0 ~ 0,
    .default = colonization_numerator/colonization_denominator)) %>% 
  select(seedling_id, repot_col) %>% 
  left_join(harvest_tips %>% 
              mutate(harvest_col = case_when(
                    colonized == 0 ~ 0,
                    .default =colonized/(colonized+uncolonized))) %>% 
              select(seedling_id, harvest_col) %>% 
              mutate(seedling_id = as.numeric(seedling_id)))

drought_treat = health %>% 
  select(seedling_id, treatment) %>% distinct()

total_treat = measure %>% 
  select(seedling_id, seedling_sp, soil_type, neighbor, neighb_sp, neighb_st, pot) %>% distinct() %>% drop_na()

sort_string_chars <- function(s) {
  paste(sort(unlist(strsplit(s, ""))), collapse = "")}

pot_df = neighb_pairs %>% 
  rename(seedling_id = seedling_1) %>% 
  left_join(trt) %>% 
  rename(sp1 = seedling_sp, st1 = soil_type) %>% 
  select(!seedling_id) %>% 
  rename(seedling_id = seedling_2) %>% 
  left_join(trt)%>% 
  rename(sp2 = seedling_sp, st2 = soil_type) %>% 
  mutate(spp = paste0(sp1, sp2))%>% 
  mutate(stt = paste0(st1, st2)) %>% 
  select(pot, spp, stt) %>% 
  mutate(spp = map_chr(spp, sort_string_chars)) %>% #alphabetize the combo to minimize different uniques
  mutate(stt = map_chr(stt, sort_string_chars)) %>% 
  left_join(drought)

living = measure %>% 
  filter(date == "2022-04-01") %>% 
  filter(alive ==1) %>% 
  select(seedling_id)
```

```{r}
ndvi = health %>% 
  select(2:6) %>% 
  left_join(total_treat) %>% 
  left_join(drought_treat)  %>% 
  group_by(seedling_id) %>% 
  mutate(ndvi = mean(mean_ndvi)) %>% 
  left_join(total_treat) %>% left_join(drought_treat)%>% 
  mutate(home_rank = case_when(
    soil_type == seedling_sp & neighb_sp == soil_type & soil_type==neighb_st ~ "Both",
    soil_type == seedling_sp ~ "Self",
    seedling_sp == neighb_st ~ "Neighbor",
    .default = "None"
  )) %>% 
  mutate(home_rank = factor(home_rank, levels = c("None", "Neighbor", "Self", "Both"))) %>% 
  filter(!is.na(seedling_sp))%>% 
  mutate(sp_long = case_when(
    seedling_sp == "P" ~ "Bigcone",
    seedling_sp == "Q" ~ "Oak"
  )) %>% 
  filter(seedling_id %in% living$seedling_id)

drought_treat = health %>% 
  select(seedling_id, treatment) %>% distinct()
total_treat = measure %>% 
  select(seedling_id, seedling_sp, soil_type, neighbor, neighb_sp, neighb_st, pot) %>% distinct() %>% drop_na() %>% 
  left_join(drought_treat)
  plotset = measure %>% 
  left_join(total_treat) %>% left_join(drought_treat)%>% 
  filter(!is.na(treatment))
```

```{r}
measure = read_csv(here("data", "seedling_measurements/size_master_all.csv"))
repot_scan = read_csv(here("data/repotting", "seedling_scan_data.csv")) %>% 
  select(-seedling_sp, -notes)
repot_mass = read_csv(here("data", "repotting", "repotting_drymass_fitted.csv"))
harvest_mass = read_csv(here("data", "harvest", "harvest_biomass_wideclean.csv")) %>% 
  mutate(total = root+shoot+foliar)
health = read_csv(here("data", "analysis/ndvi_data.csv")) 
image_data = read_csv(here("data", "wide_final_seedling_area.csv")) %>% 
  rename(img_foliar = foliar)

drought_treat = health %>% 
  select(seedling_id, treatment) %>% distinct()
total_treat = measure %>% 
  select(seedling_id, seedling_sp, soil_type, neighbor, neighb_sp, neighb_st, pot) %>% distinct() %>% drop_na() %>% 
  left_join(drought_treat)

  plotset = measure %>% 
  left_join(total_treat) %>% left_join(drought_treat)%>% 
  filter(!is.na(treatment))



```
Building growth datasets
```{r}
massbuild1 = repot_mass %>% 
  select(seedling_id, above_dry, below_dry) %>% 
  rename(r_shoot = above_dry, r_root = below_dry) %>% 
  mutate(r_total = r_shoot+r_root)
massbuild2 = harvest_mass %>% 
  mutate(h_shoot = shoot+foliar)%>% 
  select(seedling_id, root, h_shoot, shoot, foliar) %>% 
  rename(h_root = root)%>% 
  mutate(h_total = h_shoot+h_root)

biomass_growth = left_join(massbuild1, massbuild2) %>% 
  mutate(g_root = (h_root-r_root)/r_root, 
         g_shoot = (h_shoot-r_shoot)/r_shoot, 
         g_total = (h_total-r_total)/r_total) %>% 
  mutate(g_rs = h_root/h_shoot -r_root/r_shoot) %>% 
  mutate(h_rs = h_root/h_shoot)
  

ht_growth = measure %>% 
  select(seedling_id, date, height_cm) %>% 
  filter(!date == "2022-07-01") %>% 
  pivot_wider(names_from = date, values_from = height_cm, names_prefix = "ht_") %>% 
  rename(mar_21 = 2, apr_21=3,dec_21=4,feb_22=5,apr_22=6,mar_23=7) %>% 
  mutate(g_total_ht = (mar_23- apr_21)/apr_21)%>% 
  mutate(g_predrought_ht = (apr_22- apr_21)/apr_21) %>% 
  select(seedling_id, g_total_ht, g_predrought_ht)

dia_growth = measure %>% 
  select(seedling_id, date, diameter_mm) %>% 
  filter(!date == "2022-07-01") %>% 
  pivot_wider(names_from = date, values_from = diameter_mm, names_prefix = "dia_") %>% 
  rename(mar_21 = 2, apr_21=3,dec_21=4,feb_22=5,apr_22=6,mar_23=7) %>% 
  mutate(g_total_dia = (mar_23- apr_21)/apr_21)%>% 
  mutate(g_predrought_dia = (apr_22- apr_21)/apr_21) %>% 
  mutate(final_dia = mar_23) %>% 
  select(seedling_id, g_total_dia, g_predrought_dia, final_dia)

all_growth = left_join(biomass_growth,  left_join(ht_growth, dia_growth)) %>% 
  drop_na() %>% 
  left_join(total_treat)%>% 
  left_join(image_data) %>% 
  left_join(living)
  


ndvi = health %>% 
  select(2:6) %>% 
  left_join(total_treat) %>% 
  left_join(drought_treat)  %>% 
  group_by(seedling_id) %>% 
  summarize(ndvi = mean(mean_ndvi)) %>% 
  left_join(total_treat) %>% left_join(drought_treat)%>% 
  mutate(home_rank = case_when(
    soil_type == seedling_sp & neighb_sp == soil_type & soil_type==neighb_st ~ "Both",
    soil_type == seedling_sp ~ "Self",
    seedling_sp == neighb_st ~ "Neighbor",
    .default = "None"
  )) %>% 
  mutate(home_rank = factor(home_rank, levels = c("None", "Neighbor", "Self", "Both"))) %>% 
  filter(!is.na(seedling_sp))%>% 
  mutate(sp_long = case_when(
    seedling_sp == "P" ~ "Bigcone",
    seedling_sp == "Q" ~ "Oak"
  )) 
```

```{r}
totmod = lm(ndvi~soil_type*neighb_sp*neighb_st*treatment, data = all_growth %>%
              filter(seedling_sp=="P") %>% 
              left_join(ndvi)) ##includes non-living individuals


totmod_select = MASS::stepAIC(totmod)

summary(eval(totmod_select$call))
```
```{r}
surviving = measure %>% 
  filter(date == "2023-03-01") %>% 
  mutate(home_rank = case_when(
    soil_type == seedling_sp  & soil_type==neighb_st ~ "Both",
    soil_type == "C" & soil_type==neighb_st ~ "Sterile",
    soil_type == seedling_sp ~ "Self",
    seedling_sp == neighb_st ~ "Neighbor",
    .default = "None"
  ))%>% 
  mutate(home_rank = factor(home_rank, levels = c("Sterile", "None", "Neighbor", "Self", "Both"))) %>% 
  group_by(seedling_sp, home_rank, treatment, alive) %>% 
  summarize(count =n())

surv_wide = surviving %>% pivot_wider(names_from = alive, values_from = count, names_prefix = "alive_") %>% 
  mutate(alive_1 = case_when(is.na(alive_1) ~0, .default = alive_1)) %>% 
  mutate(alive_0 = case_when(is.na(alive_0) ~0, .default = alive_0))%>% 
  mutate(survival = alive_1/(alive_0+alive_1)) 
  

ggplot(surv_wide, aes(x = home_rank, y = survival, fill = treatment))+
  geom_bar(stat = "identity", position = position_dodge())+facet_wrap(~seedling_sp)+gg_droughtfill

ggplot(surv_wide, aes(x = home_rank, y = survival, color = treatment))+
  geom_point()+geom_line()+facet_wrap(~seedling_sp)+gg_droughtcolor


all_trt = all_growth%>% 
  mutate(home_rank = case_when(
    soil_type == seedling_sp  & soil_type==neighb_st ~ "Both",
    soil_type == "C" & soil_type==neighb_st ~ "Sterile",
    soil_type == seedling_sp ~ "Self",
    seedling_sp == neighb_st ~ "Neighbor",
    .default = "None"
  ))%>% 
  mutate(home_rank = factor(home_rank, levels = c("Sterile", "None", "Neighbor", "Self", "Both")))

ggplot(all_trt, aes(x = home_rank, y = h_total, fill = treatment))+
  geom_boxplot(outlier.shape = NA)+facet_wrap(~seedling_sp, scales = "free")+gg_droughtfill

ggplot(all_trt, aes(x = home_rank, y = h_shoot, fill = treatment))+
  geom_boxplot(outlier.shape = NA)+facet_grid(rows = vars(seedling_sp), cols = vars(neighb_sp), scales = "free")+gg_droughtfill

ggplot(all_trt, aes(x = home_rank, y = h_shoot, fill = neighb_sp))+
  geom_boxplot(outlier.shape = NA)+facet_grid(rows = vars(seedling_sp), cols = vars(treatment), scales = "free")
```

```{r}
surviving = measure %>% 
  filter(date == "2023-03-01") %>% 
  mutate(home_rank = case_when(
    soil_type == seedling_sp  & soil_type==neighb_st ~ "Both",
    soil_type == "C" & soil_type==neighb_st ~ "Sterile",
    soil_type == seedling_sp ~ "Self",
    seedling_sp == neighb_st ~ "Neighbor",
    .default = "None"
  ))%>% 
  mutate(home_rank = factor(home_rank, levels = c("Sterile", "None", "Neighbor", "Self", "Both"))) %>% 
  group_by(seedling_sp, home_rank, treatment, alive, neighb_sp) %>% 
  summarize(count =n())%>% 
  mutate(nsp_long = case_when(
  neighb_sp == "P"~ "n. Bigcone",
  neighb_sp == "Q"~ "n. Oak"
  ))

surv_wide = surviving %>% pivot_wider(names_from = alive, values_from = count, names_prefix = "alive_") %>% 
  mutate(alive_1 = case_when(is.na(alive_1) ~0, .default = alive_1)) %>% 
  mutate(alive_0 = case_when(is.na(alive_0) ~0, .default = alive_0)) %>% 
  mutate(survival = alive_1/(alive_0+alive_1)) 
  

ggplot(surv_wide, aes(x = home_rank, y = survival, fill = treatment))+
  geom_bar(stat = "identity", position = position_dodge())+facet_wrap(seedling_sp~nsp_long)+gg_droughtfill


ggplot(surv_wide, aes(x = home_rank, y = survival, color = treatment))+
  geom_point()+facet_wrap(seedling_sp~nsp_long)+gg_droughtcolor
```

```{r}
tov = aov(h_total~treatment*soil_type, data = all_growth %>%
              filter(seedling_sp=="P"))
TukeyHSD(tov)
```




```{r}
new = all_growth%>% 
  group_by(seedling_sp, soil_type, neighb_sp) %>% 
  mutate(al_as = img_foliar/(pi*(0.5*final_dia)^2)) %>% 
  mutate(al_as = img_foliar/final_dia) %>% 
  mutate(fol = (img_foliar-mean(img_foliar))/sd(img_foliar)) %>% 
  mutate(alas = (al_as-mean(al_as))/sd(al_as))  %>% 
  left_join(ndvi)


ggplot(new, aes(x = alas, y = ndvi, col = treatment))+
  geom_point()+facet_grid(soil_type~seedling_sp, scales = "free")+gg_droughtcolor+geom_smooth(method = "lm")
```


## Building the flow shart (bigcones first)
```{r}

species = "P"

test_sp = all_growth %>% filter(seedling_sp == species) 

#repot total size? 
TukeyHSD(aov(g_total~soil_type, data = test_sp))
#repot r:s
TukeyHSD(aov(g_root/g_shoot~soil_type, data = test_sp))
#repot shoot
TukeyHSD(aov(g_shoot~soil_type, data = test_sp))
#repot root
TukeyHSD(aov(g_root~soil_type, data = test_sp))
```


```{r}
species = "Q"
soil = "P"

###  Have now clarified soil type ###

test_st = all_growth %>% 
  filter(seedling_sp == species) %>% 
  filter(soil_type == soil) 

TukeyHSD(aov(g_total~neighb_sp, data = test_st))
TukeyHSD(aov(g_root~neighb_sp, data = test_st))
TukeyHSD(aov(g_shoot~neighb_sp, data = test_st))
TukeyHSD(aov(g_rs~neighb_sp, data = test_st))

TukeyHSD(aov(h_total~neighb_sp, data = test_st))
TukeyHSD(aov(h_root~neighb_sp, data = test_st))
TukeyHSD(aov(h_shoot~neighb_sp, data = test_st))
TukeyHSD(aov(h_rs~neighb_sp, data = test_st))
```


```{r}
### Have now clarified neighbor species ###
species = "Q"
soil = "C"
species2 = "Q"

test_nsp = all_growth %>% 
  filter(seedling_sp == species) %>% 
  filter(soil_type == soil)  %>% 
  filter(neighb_sp == species2)

TukeyHSD(aov(g_total~neighb_st, data = test_nsp))
TukeyHSD(aov(g_root~neighb_st, data = test_nsp))
TukeyHSD(aov(g_shoot~neighb_st, data = test_nsp))
TukeyHSD(aov(g_rs~neighb_st, data = test_nsp))

TukeyHSD(aov(h_total~neighb_st, data = test_nsp))
TukeyHSD(aov(h_root~neighb_st, data = test_nsp))
TukeyHSD(aov(h_shoot~neighb_st, data = test_nsp))
TukeyHSD(aov(h_rs~neighb_st, data = test_nsp))
```


```{r}
### Have now clarified neighbor soil ###
species = "Q"
soil = "C"
species2 = "Q"
neighbor_soil = "C"

test_nst = all_growth %>% 
  filter(seedling_sp == species) %>% 
  filter(soil_type == soil)  %>% 
  filter(neighb_sp == species2) %>% 
  filter(neighb_st == neighbor_soil)

TukeyHSD(aov(g_total~treatment, data = test_nst))
TukeyHSD(aov(g_root~treatment, data = test_nst))
TukeyHSD(aov(g_shoot~treatment, data = test_nst))
TukeyHSD(aov(g_rs~treatment, data = test_nst))
TukeyHSD(aov(h_total~treatment, data = test_nst))
TukeyHSD(aov(h_root~treatment, data = test_nst))
TukeyHSD(aov(h_shoot~treatment, data = test_nst))
TukeyHSD(aov(h_rs~treatment, data = test_nst))
```


```{r}
all_ndvi = all_growth %>% 
  left_join(ndvi_mean)

species = "Q"

test_sp = all_ndvi %>% filter(seedling_sp == species) 

TukeyHSD(aov(ndvi~soil_type, data = test_sp))
```


```{r}
 
species = "Q"
soil = "P"

###  Have now clarified soil type ###

test_st = all_ndvi %>% 
  filter(seedling_sp == species) %>% 
  filter(soil_type == soil) 

TukeyHSD(aov(ndvi~neighb_sp, data = test_st))

```


```{r}
### Have now clarified neighbor species ###
species = "Q"
soil = "Q"
species2 = "P"

test_nsp = all_ndvi %>% 
  filter(seedling_sp == species) %>% 
  filter(soil_type == soil)  %>% 
  filter(neighb_sp == species2)

TukeyHSD(aov(ndvi~neighb_st, data = test_nsp))
```


```{r}
### Have now clarified neighbor soil ###
species = "Q"
soil = "Q"
species2 = "Q"
neighbor_soil = "C"

test_nst = all_ndvi %>% 
  filter(seedling_sp == species) %>% 
  filter(soil_type == soil)  %>% 
  filter(neighb_sp == species2) %>% 
  filter(neighb_st == neighbor_soil)

TukeyHSD(aov(ndvi~treatment, data = test_nst))
```

```{r}
reps = measure %>% 
  filter(date == "2023-03-01") %>% 
  group_by(seedling_sp, soil_type, neighb_sp, neighb_st, treatment) %>% 
  summarize(reps = n()) %>% 
  filter(reps>1)

living_reps = measure %>% 
  filter(date == "2023-03-01") %>% 
  filter(alive == 1) %>% 
  group_by(seedling_sp, soil_type, neighb_sp, neighb_st, treatment) %>% 
  summarize(livereps = n()) %>% 
  filter(livereps>1)


wide_reps = reps %>% 
  left_join(living_reps) %>% 
  mutate(livereps = case_when(
    is.na(livereps)~0,
    .default = livereps
  )) %>% 
  mutate(pct_survival = livereps/reps)

surv_plotset = wide_reps %>% 
  mutate(state = "b_Alive") %>% 
  bind_rows(wide_reps %>% 
              mutate(pct_survival= 1-pct_survival) %>% 
              mutate(state = "a_Dead")) %>% 
  mutate(nsp_long = case_when(
  neighb_sp == "P"~ "n. Bigcone",
  neighb_sp == "Q"~ "n. Oak"
  ))%>% 
  mutate(nst_long = case_when(
  neighb_st == "P"~ "n. Bigcone soil",
  neighb_st == "Q"~ "n. Oak soil",
  neighb_st == "C"~ "n. Sterile soil"
  )) %>% 
  mutate(st_long = case_when(
  soil_type == "P"~ "Bigcone soil",
  soil_type == "Q"~ "Oak soil",
  soil_type == "C"~ "Sterile soil"
  ))%>% 
  mutate(trt_long = case_when(
  treatment == "C"~ "Watered",
  treatment == "D"~ "Drought"
  ))%>% 
  mutate(neighbor = paste0(nsp_long, "\n", nst_long))

ggplot(surv_plotset %>%  filter(seedling_sp == "P"),
       aes(x = interaction(neighb_sp, neighb_st), y = pct_survival, fill = state))+
  geom_bar(stat= "identity")+facet_grid(soil_type~treatment)+gg_nsoilcolor

psurv = ggplot(surv_plotset %>%  filter(seedling_sp == "P"),
       aes(x = neighbor, y = pct_survival, fill = state))+
  geom_bar(stat= "identity")+facet_grid(st_long~trt_long)+gg_nsoilcolor+
  labs(x = "Neighbor treatment", y = "Percent survival", title = "Bigcone survival")+
  scale_fill_manual(name = "Survival", breaks = c("a_Dead", "b_Alive"), labels = c("Dead", "Alive"), values = c("#EBD494", "#588B8B"))+
  theme_minimal()

qsurv = ggplot(surv_plotset %>%  filter(seedling_sp == "Q"),
       aes(x = neighbor, y = pct_survival, fill = state))+
  geom_bar(stat= "identity")+facet_grid(st_long~trt_long)+gg_nsoilcolor+
  labs(x = "Neighbor treatment", y = "Percent survival", title = "Oak survival")+
  scale_fill_manual(name = "Survival", breaks = c("a_Dead", "b_Alive"), labels = c("Dead", "Alive"), values = c("#EBD494", "#588B8B"))+
  theme_minimal()



library(patchwork)
survplot = psurv/qsurv

ggsave(plot = survplot, here("figures", "survival.jpg"), width = 10, height = 10)
```

```{r}
surv_plotset = wide_reps %>% 
  mutate(state = "b_Alive") %>% 
  bind_rows(wide_reps %>% 
              mutate(pct_survival= 1-pct_survival) %>% 
              mutate(state = "a_Dead")) %>% 
  mutate(nsp_long = case_when(
  neighb_sp == "P"~ "n. Bigcone",
  neighb_sp == "Q"~ "n. Oak"
  ))%>% 
  mutate(nst_long = case_when(
  neighb_st == "P"~ "n. Bigcone soil",
  neighb_st == "Q"~ "n. Oak soil",
  neighb_st == "C"~ "n. Sterile soil"
  )) %>% 
  mutate(st_long = case_when(
  soil_type == "P"~ "Bigcone soil",
  soil_type == "Q"~ "Oak soil",
  soil_type == "C"~ "Sterile soil"
  ))%>% 
  mutate(trt_long = case_when(
  treatment == "C"~ "Watered",
  treatment == "D"~ "Drought"
  ))%>% 
  mutate(neighbor = paste0(nsp_long, "\n", nst_long))


soil =  measure %>% 
  filter(date == "2023-03-01") %>% 
  group_by(seedling_sp, soil_type, treatment) %>% 
  summarize(reps = n()) %>% 
  filter(reps>1)

soil_alive =  measure %>% 
  filter(alive == 1) %>% 
  filter(date == "2023-03-01") %>% 
  group_by(seedling_sp, soil_type, treatment) %>% 
  summarize(livereps = n()) %>% 
  filter(livereps>1)

soils = soil %>% 
  left_join(soil_alive) %>% 
  mutate(pct_alive = livereps/reps)%>% 
  mutate(st_long = case_when(
  soil_type == "P"~ "Bigcone soil",
  soil_type == "Q"~ "Oak soil",
  soil_type == "C"~ "Sterile soil"
  ))%>% 
  mutate(trt_long = case_when(
  treatment == "C"~ "Watered",
  treatment == "D"~ "Drought"
  )) %>% 
  mutate(dead = reps-livereps)

ggplot(soils ,
       aes(x = soil_type, y = pct_alive, fill = treatment))+
  geom_bar(stat= "identity", position = "dodge")+facet_grid(~seedling_sp)+gg_nsoilcolor+
  labs(x = "Soil type", y = "Percent survival", title = " survival")+
  theme_minimal()+gg_droughtfill


chi_pc = soils %>% 
  ungroup() %>% 
  filter(seedling_sp== "P") %>% 
  filter(soil_type == "C") %>% 
  select(livereps, dead, trt_long) %>% 
  relocate(trt_long)

as.matrix(chi_pc[,2:3])

chisq.test(as.matrix(chi_pc[,2:3]))


ld =  measure %>% 
  filter(date == "2023-03-01") %>% 
  group_by(seedling_sp, soil_type, alive) %>% 
  summarize(reps = n()) %>% 
  filter(reps>1) %>% 
  pivot_wider(names_from = alive, values_from = reps, names_prefix = "alive_") %>% 
  filter(seedling_sp == "P")

ld
result = chisq.test(as.matrix(ld[,3:4]))
result

ld =  measure %>% 
  filter(date == "2023-03-01") %>% 
  group_by(seedling_sp, treatment, alive) %>% 
  summarize(reps = n()) %>% 
  filter(reps>1) %>% 
  pivot_wider(names_from = alive, values_from = reps, names_prefix = "alive_") %>% 
  filter(seedling_sp == "Q")

ld
result = chisq.test(as.matrix(ld[,3:4]))
result


ld =  measure %>% 
  filter(date == "2023-03-01") %>% 
  filter(!soil_type=="C") %>% 
  group_by(seedling_sp, soil_type, alive) %>% 
  summarize(reps = n()) %>% 
  filter(reps>1) %>% 
  pivot_wider(names_from = alive, values_from = reps, names_prefix = "alive_") %>% 
  filter(seedling_sp == "Q")

ld
result = chisq.test(as.matrix(ld[,3:4]))
result

```


## Survival table

```{r}
surv_table = wide_reps %>% 
  mutate(sp_long = case_when(
  seedling_sp == "P"~ "Bigcone",
  seedling_sp == "Q"~ "Oak"
  ))%>% 
  mutate(nsp_long = case_when(
  neighb_sp == "P"~ "Bigcone",
  neighb_sp == "Q"~ "Oak"
  ))%>% 
  mutate(nst_long = case_when(
  neighb_st == "P"~ "Bigcone soil",
  neighb_st == "Q"~ "Oak soil",
  neighb_st == "C"~ "Sterile soil"
  )) %>% 
  mutate(st_long = case_when(
  soil_type == "P"~ "Bigcone soil",
  soil_type == "Q"~ "Oak soil",
  soil_type == "C"~ "Sterile soil"
  ))%>% 
  mutate(trt_long = case_when(
  treatment == "C"~ "Watered",
  treatment == "D"~ "Drought"
  )) %>% 
  ungroup() %>% 
  select(9:13, 6,8) %>% 
  pivot_wider(names_from = trt_long, values_from = c(reps, pct_survival)) %>% 
  relocate(1:4, 5,7,6,8) %>% 
  mutate(tot_surv = (pct_survival_Watered*reps_Watered +reps_Drought*pct_survival_Drought)/(reps_Watered+reps_Drought))

surv_blanks = surv_table %>% 
  select(1:4) %>% 
  complete(sp_long, nsp_long, nst_long, st_long) %>% 
  left_join(surv_table) %>% 
  mutate(pct_survival_Watered = round(pct_survival_Watered, 3))%>% 
  mutate(pct_survival_Drought = round(pct_survival_Drought, 3))%>% 
  mutate(tot_surv = round(tot_surv, 3)) %>%
  mutate(across(where(is.numeric), ~ if_else(is.na(.), "--", as.character(.)))) %>% 
  arrange(sp_long, st_long, nsp_long, nst_long)%>% 
  relocate(1,4,2,3,5:9)

surv_print = surv_blanks %>% 
  rename("Seedling sp."=1, "Soil type"=2,"Neighbor sp."=3,"Neighbor soil"=4,
         "n Watered"=5,"% Surv. Watered"=6,"n Droughted"=7,"% Surv. Droughted"=8,"Total % survival"=9)




kable(surv_print) %>%
  kable_styling() %>%
  kable_classic(full_width = F, html_font = "Cambria") %>%
  row_spec(0:nrow(surv_print), extra_css = "height: 2px;")%>%
  save_kable(here("figures", "surv_table.html"))
```


